### ISSUE TITLE
No clean "ID" for Ubuntu repo's

### ISSUE THREAD

**Issue by litebito** [furlongm/patchman#104]
Most of my hosts are CentOS(7), some are Ubuntu (because of restrictions)
CenOS repo's seem to get a clean representation in the repo's overview, however, Those for Ubuntu are not, it just shows the raw info and URL, no ID, no clean representation.
See attached screenshot on what I mean.

Can that be fixed?

![image](https://user-images.githubusercontent.com/3867999/57180097-886c1080-6e85-11e9-8bc3-503da4f70c35.png)

**Comment by furlongm** [comment]
apt repos are not like yum repos in that they don't have a "name". Without a name it's not possible to represent them the same way as yum repos. You can however rename the repos as you see fit via the web interface.
