### ISSUE TITLE
patchman client installation documantation

### ISSUE THREAD

**Issue by obalouchi1** [furlongm/patchman#121]
Hello, thanks for your great work. 

I managed to install the patchman and on the server side. I don't find any docs for installing it on client hosts and where to add the IP address in order to communicate with the server. 

Also when I run patchman on server side, it seems it doesnt find anything. 

 patchman -a
/usr/local/lib/python2.7/dist-packages/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
Cleaning Reports for all Hosts

Processing Reports for all Hosts
No orphaned Packages found.
No orphaned Package names found.
No orphaned Package Architectures found.
No orphaned Machine Architectures found.
No Repositories with zero Mirrors found.
Refreshing metadata for all Repos

Finding updates for all Hosts

No orphaned Packages found.
No orphaned Package names found.
No orphaned Package Architectures found.
No orphaned Machine Architectures found.
No Repositories with zero Mirrors found.
Checking rDNS for all Hosts

Processing 196 Errata:             100%|#############################################################|Time: 0:00:00
Scanning 195 Errata:               100%|#############################################################|Time: 0:00:00

**Comment by furlongm** [comment]
It won't find anything until you submit a report.

Too submit a report from the  client, try running patchman-client -s $SERVER
e.g.

```
patchman-client -s http://127.0.0.1/patchman
```

on the server where you installed the patchman package.

See https://github.com/furlongm/patchman/blob/master/INSTALL.md for more details.
