### ISSUE TITLE
Security updates pending : difference between patchman and yum

### ISSUE THREAD

**Issue by litebito** [furlongm/patchman#124]
Hi,

Because I wanted to automate security updates on my CentOS hosts, I was looking at using yum-cron.

But, when I started to check, although Yum tells me there are no security updates, Patchman does.
How are security updates categorized in patchman?
Example : for a specific host, patchman shows 11 security updates and 17 normal updates pending.
However, when on that host, I do a "yum --security update", yum tells me 
"No packages needed for security; 28 packages available"

(I did run patchman client, and patchman server a few times to make sure they are in sync)

![2019-08-15 11_55_11](https://user-images.githubusercontent.com/3867999/63088325-e7492780-bf54-11e9-82b5-b1de1569004e.png)
![2019-08-15 11_53_38-Patchman Dashboard](https://user-images.githubusercontent.com/3867999/63088326-e7492780-bf54-11e9-8f18-40c3e05f1e2e.png)

**Comment by furlongm** [comment]
Security update status is taken from https://cefs.steve-meier.de/

**Comment by litebito** [comment]
I've read up, on how where he gets his source from.
It looks like whatever is announced to the mailinglist as a bugfix security is considered as a security update, so it has nothing to do with security updates in yum.
Sad that the people at CentOS are not properly aligned in this.
I was hoping to fully automate security updates on my hosts the easy way.

**Comment by furlongm** [comment]
yum on RHEL provides the correct output, but not CentOS. I'll close this issue as patchman provides more information than CentOS does, so there is nothing further we can do on the patchman end,
