### ISSUE TITLE
No counters after install/addings hosts

### ISSUE THREAD

**Issue by ikheetleon** [furlongm/patchman#136]
I've installed patchman on a Centos 7 machine. Followed the instructions, using mysql. 
Hosts are added, but update counters are not shown. I've run patchman -a several times on the patchman server. Any hints? See screenshot. I've enabled debug, but am not sure where to look for the debug log file. 

![afbeelding](https://user-images.githubusercontent.com/2777560/64956691-7f576b00-d88b-11e9-942c-65a3b23a092c.png)

Another thing, is there a way to disable rdns check by default?

**Comment by skatsaounis** [comment]
Hi @ikheetleon,

Speaking about the rdns check all you have to do is to set a model field to False: https://github.com/furlongm/patchman/blob/master/hosts/models.py#L48

I would like the default value to be false as well but until then I am running a one liner before each patchman -a command:

```
from patchman.hosts.models import Host
hosts = Host.objects.filter(check_dns=True).update(check_dns=False)
````

It is not the prettiest solution but still you could try this out.

**Comment by ikheetleon** [comment]
Thanks for your comment about rdns, I will use that.
Regarding my first issue, something was wrong with the installation, not sure what. Made a fresh install and it now works.
