### ISSUE TITLE
Disable or external authentication 

### ISSUE THREAD

**Issue by ikheetleon** [furlongm/patchman#141]
I'm not very experienced with Django, is there a way to disable authentication? I've seen a ticket about ldap authentication, that would be an option too, but I'm not sure what files to edit to get it working. They other option is to disable it and set a revproxy in front that does authentication.

**Comment by furlongm** [comment]
The following url seems to answer your question:

https://stackoverflow.com/questions/42253917/disable-all-authentication-django?rq=1
