### ISSUE TITLE
Wrong "Last Report" on Host view

### ISSUE THREAD

**Issue by ptrsny** [furlongm/patchman#143]
The Host table view has a column named "Last Report", which does not show the correct last report date for that host, except the "Last Update" field of that  host is the same as the "Last Report" field.

It would be nice to see both the "Last Update" and the "Last Report" value on the host view.

**Comment by ptrsny** [comment]
Host Table entry:
![patchman_issue_143_host_table](https://user-images.githubusercontent.com/14097379/67576700-53a78a80-f73f-11e9-9514-fcea05abe581.png)

Host Detail View:
![patchman_issue_143_host_detail](https://user-images.githubusercontent.com/14097379/67576749-6cb03b80-f73f-11e9-9e11-464067a1aedb.png)

last Report (30.09.):
![patchman_issue_143_report_30](https://user-images.githubusercontent.com/14097379/67576782-7e91de80-f73f-11e9-9569-b79b732fd975.png)

"first" Report (29./28.09.):
![patchman_issue_143_report_29_28](https://user-images.githubusercontent.com/14097379/67576825-9a958000-f73f-11e9-8c1f-32acd037dc9c.png)

Look that between the two reports the ip address changed. Hostname and Domain are exactly the same.

PS.: the last report says 28.09. and the host detail view says 29.09. witch comes from the different timezone representation of naiv and non-naiv timestamps.

**Comment by furlongm** [comment]
Last update for the host (`host.updated_at`), and (`report.created_at`) for a report are different things. The host object will be updated e.g. when new package updates are found for that host (irrespective of whether a new report has come in).

**Comment by furlongm** [comment]
Having said that, maybe the timezone representations in both `host` and `report` could be aligned. Also, `report.accessed_at` seems to be superfluous
