### ISSUE TITLE
/patchman/login/?next=/patchman/dashboard/ DoesNotExist, Site matching query does not exist.

### ISSUE THREAD

**Issue by litebito** [furlongm/patchman#145]
Hi,

I'm suddenly finding myself with the following error when I try to go to the patchman dashboard.

patchman-server on the command line still runs fine
and clients are still able to send their report to the patchman server

I'm not sure if the cause is a crash of the server, or an update

Anyone has any ideas?

`Request Method: | GET
-- | --
http://xxxx/patchman/login/?next=/patchman/dashboard/
1.11.23
DoesNotExist
Site matching query does not exist.
/usr/lib/python2.7/site-packages/django/db/models/query.py in get, line 380
/usr/bin/python
2.7.5
['/usr/lib64/python27.zip',  '/usr/lib64/python2.7',  '/usr/lib64/python2.7/plat-linux2',  '/usr/lib64/python2.7/lib-tk',  '/usr/lib64/python2.7/lib-old',  '/usr/lib64/python2.7/lib-dynload',  '/usr/lib64/python2.7/site-packages',  '/usr/lib/python2.7/site-packages']
Tue, 12 Nov 2019 17:02:32 +0100`

**Comment by furlongm** [comment]
Can you confirm if you have `SITE_ID = 1` in your settings?

**Comment by litebito** [comment]
Hi,

Is this a new requirement?

I added it here, and restarted, but it does not seem to change much

`[root@host patchman]# cat local_settings.py
# Django settings for patchman project.
SITE_ID = 1

DEBUG = True

ADMINS = (
    ('Your Name', 'you@example.com'),
)

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': '/var/lib/patchman/db/patchman.db',
    }
}

# Local time zone for this installation. Choices can be found here:
# http://en.wikipedia.org/wiki/List_of_tz_zones_by_name
TIME_ZONE = 'Europe/Brussels'

# Language code for this installation. All choices can be found here:
# http://www.i18nguy.com/unicode/language-identifiers.html
LANGUAGE_CODE = 'en-us'

# Create a unique string here, and don't share it with anybody.
SECRET_KEY = something

# Add the IP addresses that your web server will be listening on,
# instead of '*'
ALLOWED_HOSTS = ['127.0.0.1', '*']
#ALLOWED_HOSTS = ['*']

# Maximum number of mirrors to add or refresh per repo
MAX_MIRRORS = 5

# Number of days to wait before notifying users that a host has not reported
DAYS_WITHOUT_REPORT = 14

# Whether to run patchman under the gunicorn web server
RUN_GUNICORN = False

# Enable memcached
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION': '127.0.0.1:11211',
    }
}

[root@host patchman]# `


full trace :

`Environment:


Request Method: GET
Request URL: http://netman02/patchman/login/?next=/patchman/dashboard/

Django Version: 1.11.23
Python Version: 2.7.5
Installed Applications:
[u'django.contrib.admin',
 u'django.contrib.auth',
 u'django.contrib.contenttypes',
 u'django.contrib.sessions',
 u'django.contrib.messages',
 u'django.contrib.staticfiles',
 u'django.contrib.humanize',
 u'django.contrib.admindocs',
 u'django.contrib.sites',
 u'django_extensions',
 u'tagging',
 u'bootstrap3',
 u'rest_framework',
 u'arch.apps.ArchConfig',
 u'domains.apps.DomainsConfig',
 u'hosts.apps.HostsConfig',
 u'operatingsystems.apps.OperatingsystemsConfig',
 u'packages.apps.PackagesConfig',
 u'repos.apps.ReposConfig',
 u'reports.apps.ReportsConfig',
 u'util.apps.UtilConfig']
Installed Middleware:
[u'django.middleware.security.SecurityMiddleware',
 u'django.contrib.sessions.middleware.SessionMiddleware',
 u'django.middleware.common.CommonMiddleware',
 u'django.middleware.csrf.CsrfViewMiddleware',
 u'django.contrib.auth.middleware.AuthenticationMiddleware',
 u'django.contrib.messages.middleware.MessageMiddleware',
 u'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback:

File "/usr/lib/python2.7/site-packages/django/core/handlers/exception.py" in inner
  41.             response = get_response(request)

File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/usr/lib/python2.7/site-packages/django/views/generic/base.py" in view
  68.             return self.dispatch(request, *args, **kwargs)

File "/usr/lib/python2.7/site-packages/django/utils/decorators.py" in _wrapper
  67.             return bound_func(*args, **kwargs)

File "/usr/lib/python2.7/site-packages/django/views/decorators/debug.py" in sensitive_post_parameters_wrapper
  76.             return view(request, *args, **kwargs)

File "/usr/lib/python2.7/site-packages/django/utils/decorators.py" in bound_func
  63.                 return func.__get__(self, type(self))(*args2, **kwargs2)

File "/usr/lib/python2.7/site-packages/django/utils/decorators.py" in _wrapper
  67.             return bound_func(*args, **kwargs)

File "/usr/lib/python2.7/site-packages/django/utils/decorators.py" in _wrapped_view
  149.                     response = view_func(request, *args, **kwargs)

File "/usr/lib/python2.7/site-packages/django/utils/decorators.py" in bound_func
  63.                 return func.__get__(self, type(self))(*args2, **kwargs2)

File "/usr/lib/python2.7/site-packages/django/utils/decorators.py" in _wrapper
  67.             return bound_func(*args, **kwargs)

File "/usr/lib/python2.7/site-packages/django/views/decorators/cache.py" in _wrapped_view_func
  57.         response = view_func(request, *args, **kwargs)

File "/usr/lib/python2.7/site-packages/django/utils/decorators.py" in bound_func
  63.                 return func.__get__(self, type(self))(*args2, **kwargs2)

File "/usr/lib/python2.7/site-packages/django/contrib/auth/views.py" in dispatch
  90.         return super(LoginView, self).dispatch(request, *args, **kwargs)

File "/usr/lib/python2.7/site-packages/django/views/generic/base.py" in dispatch
  88.         return handler(request, *args, **kwargs)

File "/usr/lib/python2.7/site-packages/django/views/generic/edit.py" in get
  174.         return self.render_to_response(self.get_context_data())

File "/usr/lib/python2.7/site-packages/django/contrib/auth/views.py" in get_context_data
  124.         current_site = get_current_site(self.request)

File "/usr/lib/python2.7/site-packages/django/contrib/sites/shortcuts.py" in get_current_site
  15.         return Site.objects.get_current(request)

File "/usr/lib/python2.7/site-packages/django/contrib/sites/models.py" in get_current
  63.             return self._get_site_by_id(site_id)

File "/usr/lib/python2.7/site-packages/django/contrib/sites/models.py" in _get_site_by_id
  35.             site = self.get(pk=site_id)

File "/usr/lib/python2.7/site-packages/django/db/models/manager.py" in manager_method
  85.                 return getattr(self.get_queryset(), name)(*args, **kwargs)

File "/usr/lib/python2.7/site-packages/django/db/models/query.py" in get
  380.                 self.model._meta.object_name

Exception Type: DoesNotExist at /login/
Exception Value: Site matching query does not exist.
`

**Comment by furlongm** [comment]
It's not a new requirement. Does a `./manage.py migrate --run-syncdb` fix it?

**Comment by furlongm** [comment]
Let me know if that fixes it for you. If not, feel free to reopen issue.

**Comment by litebito** [comment]
I'm sorry for the late reply on this one.
I had to reinstall the server to get rid of other issues
