### ISSUE TITLE
patchman-client has issues on raspbian

### ISSUE THREAD

**Issue by garbled1** [furlongm/patchman#148]
I've noticed my Raspbian PI's aren't loading repository data into patchman.  Tried running the client and got some sed errors. Here it is with bash -x:

```
++ grep -e 'Packages$'
+ nondist_repos=
+ echo '500 http://archive.raspberrypi.org/debian buster/main armhf
500 http://raspbian.raspberrypi.org/raspbian buster/rpi armhf
500 http://raspbian.raspberrypi.org/raspbian buster/non-free armhf
500 http://raspbian.raspberrypi.org/raspbian buster/contrib armhf
500 http://raspbian.raspberrypi.org/raspbian buster/main armhf'
+ sed -e 's/\([0-9]*\) \(http:.*\|https:.*\)[\/]\? \(.*\/.*\) \(.*\)/'\''deb\
'\'' \'\''Raspbian GNU/Linux armv7l repo at \2\/dists\/\3\/binary-\4'\'' '\''
\1'\'' '\''\2\/dists\/\3\/binary-\4'\''/'
sed: -e expression #1, char 82: unknown option to `s'
+ echo ''
+ sed -e 's/\([0-9]*\) \(http:.*\|https:.*\)[\/]\? \(.*\/\?.*\) Packages/'\''
deb\'\'' \'\''Raspbian GNU/Linux armv7l repo at \2\/\3'\'' '\''\1'\'' '\''\2\
/\3'\''/'
sed: -e expression #1, char 86: unknown option to `s'
+ check_command_exists zypper
++ /usr/bin/which zypper
+ cmd=
+ '[' '!' -z '' ']'
+ return 1
+ IFS=' 	
```

My guess is the "GNU/Linux" thing, where the / is ending sed?

**Comment by furlongm** [comment]
I think so. Does `/etc/os-release` exist? If so, can you paste the contents?

**Comment by garbled1** [comment]
# cat /etc/os-release 
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

Just curious, why not use sed -e @foo@bar@ instead of /foo/bar/ ?  Is @ a common character in os-release files?
