### ISSUE TITLE
problems with client getting deb/ubuntu repos properly

### ISSUE THREAD

**Issue by gasperzupancic** [furlongm/patchman#15]
We recently implemented your solution for update checking on our linux hosts. Our distributions are mainly centos and ubuntu.
Problem arises when we're adding repos for ubuntu 10 and ubuntu 16. Patchman-client for ubuntu 10 dosen't add /dists/ folder and with ubuntu 16 client misses a backslash. So what i did was to change client script to change the output and now it works, but im not sure what is the difference with dists and non-dists repos?

ubuntu 10 output was like this:
'deb' 'Ubuntu 10.04 x86_64 repo at http://security.ubuntu.com/ubuntu/lucid-security/multiverse' '500' 'http://security.ubuntu.com/ubuntu/lucid-security/multiverse'

and ubuntu 16 output was:
'deb' 'Ubuntu 16.04 x86_64 repo at http://security.ubuntu.com/ubuntudists/xenial-security/multiverse/binary-i386' '500' 'http://security.ubuntu.com/ubuntudists/xenial-security/multiverse/binary-i386'

as we changed the client side and not really understanding everything maybe you could send as more universal solution as this seems to be just a workaround.

**Comment by furlongm** [comment]
If your fix works for all intermediate debian and ubuntu versions, I'm happy to accept it. IIRC we dropped support for ubuntu 10 due to it being out of support, and I haven't had time to check ubuntu 16 yet.

For the client I was hoping to replace the bash client with a python client. I have started working on a REST API (see the rest branch). A python client could use native python objects instead of parsing the yum and apt output (which as you can see is temperamental).

**Comment by gasperzupancic** [comment]
I know ubuntu 10 is oof but we're still in the process of upgrading or replacing machines. I'll try to test it out the best i can. Can you give me some heads up with dists and non_dists version of repos? What is the difference?

**Comment by furlongm** [comment]
dist_repos are the typical debian repos.

non_dist_repos are not typically seen that often. They are repos created by the opensuse build service, see:

https://en.opensuse.org/openSUSE:Build_Service_Debian_builds#Configuring_sources.list

Note that there is no "distribution" at the end of the line in sources.list.

There was some code taken out of the client for older releases, that might still be useful for you while you migrate? See 1e016eb956addbb3fd7c1dbc99da0acf29358be3

**Comment by gasperzupancic** [comment]
what confuses me is that these two lines determines dist or non_dists packages:
dist_repos=`echo "${repos}" | grep -v -e "Packages$"`
nondist_repos=`echo "${repos}" | grep -e "Packages$"`

Acording to what you say (im in no way an expert, just a user) then dist_repos are all repos that do not contain "Packages" string. But when i checked apt-cache policy command on different ubuntu servers I always get back  lines with Packages string at the end. That way i am always getting non_dists repos?

Or it should be the other way around with your script?

**Comment by furlongm** [comment]
Maybe the naming is incorrect in my script? It doesn't matter though as the logic seems to be correct and both write to the same file, just with a different sed. Maybe I should call them something else. debian_repos and obs_repos?

**Comment by gasperzupancic** [comment]
naming is ok. it is just that i will correct the right one as not to break the working one:) or i will just add exception for ubuntu 10 as it is not supported anymore. just close this issue and we will gladly wait for python version of client and happily use a workaround until then. (im also doing some pie chart addons beacuse i like pictures as in wsus)

**Comment by gasperzupancic** [comment]
actualy i found where i failed. 

apt-cache policy on ubuntu 10 doesn't return architecture version that is why sed fails. Sorry to bother you with that. I'll make a workaround for ubuntu 10.

as for ubuntu 16 i needed to add one more \ in sed. have to test it with version 12 and 14 yet.
