### ISSUE TITLE
RHEL Repsitory update

### ISSUE THREAD

**Issue by lingej** [furlongm/patchman#159]
Hi,
how to set up the synchronization of RHEL repositories?

The Repository is protected and Patchman is running on debian 10. 

Hints are gladly accepted ;)

Joerg

```
patchman -r -R 17
Refreshing metadata for Repo 17
Repository 17 : Red Hat Enterprise Linux 7 Server - Optional (RPMs) x86_64
Repo requires certificate authentication, not updating
```

**Comment by furlongm** [comment]
If you set `host_repos_only` for each host, it should find the updates on the host, rather than on the patchman server.

**Comment by lingej** [comment]
Hi Marcus,

thanks for your Answer!

How to set host_repos_only ? Ist this an option to patchman-client?

Joerg

**Comment by furlongm** [comment]
You can set it in the django admin interface, but this might be worth adding to the `patchman` script.

**Comment by furlongm** [comment]
Can you try the change in e6f7e2c8e26f4d5047a7c605fbb9108397248a98?

**Comment by furlongm** [comment]
Cleaned up a little more in f6ba33ea95d64f31ad5113bb47cec38a66f165f4
