### ISSUE TITLE
Sed error on patchman-client run

### ISSUE THREAD

**Issue by geekix** [furlongm/patchman#161]
Hi,

First of all, thank you for this great software, it saved my a** when I was asked to keep track of which servers need to be updated. And we run a lot...

I'm having a problem with one server that throws an error when patchman-client is run :

`/usr/sbin/patchman-client -s http://patchman-server.domain.local
sed: -e expression #1, char 79: unterminated 's' command`

I took a look at the code, looking for a syntax error somewhere, even though it's the exact same script that runs fine on all our other boxes. But nothing.

As a result, a report is being generated and sent to the patchman server but the dashboard still shows available updates even if the box is fully up to date.

Here is the OS version of the server where the problem appears : CentOS Linux release 7.7.1908 (Core)

Any idea of what could cause that ? Feel free to ask for any more information.

Thanks

**Comment by furlongm** [comment]
Can you provide the full output of `/etc/os-release`?

**Comment by furlongm** [comment]
I can't reproduce this issue, but if it's still occurring feel free to reopen. Please include the output of `cat /etc/os-release`, `cat /etc/centos-release` and `bash -x patchman-client -v -d`.
