### ISSUE TITLE
Timeout on receiving repo key

### ISSUE THREAD

**Issue by nraetzer** [furlongm/patchman#164]
If I try to install patchman on my Ubuntu 18.04 LTS Server, I only get a connection time out error when I try to add the repo to apt.

`apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 0412F522
Executing: /tmp/apt-key-gpghome.o2wJ1Lhf7Q/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys 0412F522
gpg: keyserver receive failed: Connection timed out
`
Looks for me like there is something wrong with the keys for that repo.
Can someone have a look at it?

**Comment by kiranos** [comment]
How is your firewall configured, seem like you cant reach the external service which handles the keys.

**Comment by furlongm** [comment]
This sounds like a firewall issue, try with `--keyserver hkp://keyserver.ubuntu.com:80` (and/or `--keyserver-options http-proxy=${http_proxy}` if you have a proxy set).
