### ISSUE TITLE
Example how to use curl with the rest api.

### ISSUE THREAD

**Issue by kiranos** [furlongm/patchman#168]
I'm looking for an example to auth with the rest api through curl, Would be nice to have that in the README.md

I cant seem to find it anywhere, and I need it to remotely automate with patchman as data source.

**Comment by furlongm** [comment]
Patchman uses `django-rest-framework` for the REST API, so their documentation should be helpful:

https://www.django-rest-framework.org/api-guide/authentication/

**Comment by furlongm** [comment]
For  basic auth with python, you could use something like the following:

```
#!/usr/bin/env python

import json
import requests
from requests.auth import HTTPBasicAuth

protocol = 'http'
host = '35.24.228.253'
path = '/api/'

api_url = '{0!s}://{1!s}{2!s}'.format(protocol, host, path)
response = requests.get(api_url, auth=('root', 'password'))
if response.status_code == 200:
    endpoints = response.json()
    print(endpoints)
```

**Comment by furlongm** [comment]
Hope that helps!

**Comment by dandunckelman** [comment]
I was just trying to figure this out and wanted to share my solution.

I'm able to login to the dashboard with my user and pass, but when I try using `curl`, I'd get this:

```bash
# curl -v --user root:mypass localhost/patchman/api/
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 80 (#0)
* Server auth using Basic with user 'root'
> GET /patchman/api/ HTTP/1.1
> Host: localhost
> Authorization: Basic TOKEN-REDACTED
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 403 FORBIDDEN
< Date: Mon, 24 Feb 2020 20:34:24 GMT
< Server: Apache/2.4.18 (Ubuntu)
< Vary: Accept,Cookie
< Allow: GET, HEAD, OPTIONS
< Transfer-Encoding: chunked
< Content-Type: application/json
<
* Connection #0 to host localhost left intact
{"detail":"Authentication credentials were not provided."}
```

Googling `django rest framework 403 authentication credentials were not provided` led me to do this:

- Update `/etc/patchman/local_settings.py` with this:

      REST_FRAMEWORK = {
        'DEFAULT_PERMISSION_CLASSES': [
          'rest_framework.permissions.AllowAny',
        ]
      }
- Reboot VM
  - I couldn't quickly find out how to restart the server's service...and just wanted to quickly test this
- Then the curl request worked

Thanks for the awesome tool @furlongm

**Comment by furlongm** [comment]
@dandunckelman I wouldn't advise doing it that way. You are effectively turning off all auth for the REST API. The snippet above give an example of how to auth using python, and the linked documentation gives an example of how to use curl with token auth.

**Comment by dandunckelman** [comment]
@furlongm I agree and appreciate the concern, but this was just a "get it working now" solution for my internal VM where I'm unconcerned with security. Nonetheless, I'll heed your suggestion. I have updated my local settings to this:

```
REST_FRAMEWORK = {
  'DEFAULT_AUTHENTICATION_CLASSES': [
    'rest_framework.authentication.BasicAuthentication',
  ],
  'DEFAULT_PERMISSION_CLASSES': [
    'rest_framework.permissions.IsAuthenticated',
  ]
}
```

Now I get a 401 when valid authentication isn't given.

BTW, your Python example also gave me a 403 until I applied the above change. It could be something to do with my environment that led me to NEED that configuration.

Thanks again

**Comment by furlongm** [comment]
In my example, you would need to change the user and password from `'root'` and `'password'`, to your own credentials.

For the token auth, see https://www.django-rest-framework.org/api-guide/authentication/#tokenauthentication

**Comment by dandunckelman** [comment]
@furlongm Using my credentials, I was getting the 403 error with both `curl` and the Python example. It started working after I added the `REST_FRAMEWORK` section to my `local_settings.py`.

I suppose there's some other difference between our environments allowing yours to work without specifying the `REST_FRAMEWORK`. Maybe a different python or pip package version.

I just wanted to share what was missing to get this working (for me...which may be helpful for others in the future), and I greatly appreciate your having me use a more secure approach.
