### ISSUE TITLE
patchman -r failed on repos

### ISSUE THREAD

**Issue by gasperzupancic** [furlongm/patchman#17]
Today i added more servers to patchman and run the -r option to run refresh on repos. It fails on some repo like:

Found yum rpm repo - http://mirror.lihnidos.org/CentOS/7.2.1511/os/x86_64/repodata/repomd.xml
Downloading repo info (2/2):       100%|####################################################################################################################################################|Time: 0:00:00
Extracting packages:               100%|####################################################################################################################################################|Time: 0:00:03
Adding 9007 new packages:          100%|####################################################################################################################################################|Time: 0:01:05

Extra Packages for Enterprise Linux 7 - x86_64 x86_64
Traceback (most recent call last):
  File "/usr/bin/patchman", line 5, in <module>
    pkg_resources.run_script('patchman==0.9.4', 'patchman')
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 540, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1455, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/patchman-0.9.4-py2.7.egg/EGG-INFO/scripts/patchman", line 603, in <module>
    main()
  File "/usr/lib/python2.7/site-packages/patchman-0.9.4-py2.7.egg/EGG-INFO/scripts/patchman", line 597, in main
    showhelp = process_args(args)
  File "/usr/lib/python2.7/site-packages/patchman-0.9.4-py2.7.egg/EGG-INFO/scripts/patchman", line 569, in process_args
    refresh_repos(args.repo, args.force)
  File "/usr/lib/python2.7/site-packages/patchman-0.9.4-py2.7.egg/EGG-INFO/scripts/patchman", line 112, in refresh_repos
    repo.refresh(force)
  File "/usr/lib/python2.7/site-packages/patchman-0.9.4-py2.7.egg/patchman/repos/models.py", line 84, in refresh
    refresh_rpm_repo(self)
  File "/usr/lib/python2.7/site-packages/patchman-0.9.4-py2.7.egg/patchman/repos/utils.py", line 518, in refresh_rpm_repo
    mirrorlists_check(repo)
  File "/usr/lib/python2.7/site-packages/patchman-0.9.4-py2.7.egg/patchman/repos/utils.py", line 275, in mirrorlists_check
    mirror_urls = mirrorlist_check(mirror.url)
  File "/usr/lib/python2.7/site-packages/patchman-0.9.4-py2.7.egg/patchman/repos/utils.py", line 255, in mirrorlist_check
    res = get_url(mirror_url)
  File "/usr/lib/python2.7/site-packages/patchman-0.9.4-py2.7.egg/patchman/repos/utils.py", line 196, in get_url
    res = urlopen(url=Request(url), timeout=10)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 423, in open
    protocol = req.get_type()
  File "/usr/lib64/python2.7/urllib2.py", line 285, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: 5

and another where it couldnt find "<" sign but i deleted repo from database and output also. I'll do it again tomorrow when my client reports itself.

Is there an easy fix?

**Comment by gasperzupancic** [comment]
i found out that patchman somehow added miror with url 5 to the list and it of course couldn't run check on it... maybe you could put some "regex" if its actualy a url before check?

**Comment by furlongm** [comment]
Interesting. Yes, a regex would make sense. Does the mirror list return '5'
if opened in a browser?

**Comment by gasperzupancic** [comment]
One of the mirror list returns list of mirrors. This mirror fails
http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock/repodata/repomd.xml.bz2

with error : 
lxml.etree.XMLSyntaxError: Start tag expected, '<' not found, line 1, column 1

Output of the mirror is simple list of urls. Im very poor in programing but my bet is that parser expects xml but it doesn't get one. if you call this url without .bz2 you get the same list without xml tags.

**Comment by furlongm** [comment]
Hmm, might be because it ends with repomd.xml.bz2. If you change the url to
http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os does that fix
it? (You can manually change the url in the django admin interface).

On 23 May 2016 at 16:50, gasperzupancic <notifications@github.com> wrote:

> One of the mirror list returns list of mirrors. This mirror fails
>
> http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock/repodata/repomd.xml.bz2
>
> with error :
> lxml.etree.XMLSyntaxError: Start tag expected, '<' not found, line 1,
> column 1
>
> Output of the mirror is simple list of urls. Im very poor in programing
> but my bet is that parser expects xml but it doesn't get one. if you call
> this url without .bz2 you get the same list without xml tags.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/furlongm/patchman/issues/17#issuecomment-220900054>
>



-- 
Marcus Furlong

**Comment by gasperzupancic** [comment]
no luck. now it reports 
Unknown error: http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os - timed out

**Comment by gasperzupancic** [comment]
nevermind. i removed all mirrorlist. But having another problem with this repository:
https://rpm.nodesource.com/pub_5.x/el/7/x86_64/repodata/repomd.xml

it finds repomd.xml but no usable mirror found...?

[root@mirror utils]# patchman -r -R 336
Refreshing metadata for repo 336
Node.js Packages for Enterprise Linux 7 - x86_64 x86_64
https://rpm.nodesource.com/pub_5.x/el/7/x86_64/repodata/repomd.xml.bz2 - Not Found
https://rpm.nodesource.com/pub_5.x/el/7/x86_64/repodata/repomd.xml.gz - Not Found
Downloading repo info (1/2):       100%|####################################################################################################################################################|Time: 0:00:00
Found yum rpm repo - https://rpm.nodesource.com/pub_5.x/el/7/x86_64/repodata/repomd.xml
No usable mirror found at https://rpm.nodesource.com/pub_5.x/el/7/x86_64

Is there a debug option?:)

**Comment by furlongm** [comment]
If you enable DEBUG=True in settings.py this should enable some further debugging output.

**Comment by gasperzupancic** [comment]
already enabled. its just im interested why this repo is failing.

im using manual command:

patchman -r -R repo_id and get output from above.

**Comment by furlongm** [comment]
The initial issue with mirror lists should be fixed by c37a79f.

The second issue seems to be specific to the rpm.nodesource.com rpm repository. It is serving the xml.gz files with a content-type of 'text/html' instead of 'application/octet-stream'.

**Comment by gasperzupancic** [comment]
great find. tnx!

**Comment by gasperzupancic** [comment]
im back with an erorr of mirrorlist. I updated your "fix" to my install and added one host with mirrorlist repo. After playing around with client  i found out it posts this line as a repo:
'rpm' 'CentOS-7 - Extras x86_64' 'extras/7/x86_64' '99' 'http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=extras&infra=stock' 'http://ftp.arnes.si/pub/mirrors/centos.org/7.2.1511/extras/x86_64' 'more)'

This is the "problem mirror" on doing patchman -r on server. This 'more)' is added as own mirror and it fails on doing the report. What is this "more" string? It is added with regex when client sends report.

**Comment by furlongm** [comment]
Can you send me via email the patchman client outputs and files created when using -d -v?

**Comment by furlongm** [comment]
Thanks, can you check if 60181dc fixes it for you?

**Comment by gasperzupancic** [comment]
Hello i think your fix did the trick. This is (repos) post data that it sends:

'rpm' 'CentOS-7 - Base x86_64' 'base/7/x86_64' '99' 'http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock' '(9' 'more)'
'rpm' 'bintray--sbt-rpm x86_64' 'bintray--sbt-rpm' '99' 'http://dl.bintray.com/sbt/rpm'
'rpm' 'Elasticsearch repository for 2.x packages x86_64' 'elasticsearch-2.x' '99' 'https://packages.elastic.co/elasticsearch/2.x/centos'
'rpm' 'Extra Packages for Enterprise Linux 7 - x86_64 x86_64' 'epel/x86_64' '99' 'http://mirror.23media.de/epel/7/x86_64'
'rpm' 'CentOS-7 - Extras x86_64' 'extras/7/x86_64' '99' 'http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=extras&infra=stock' 'http://ftp.arnes.si/pub/mirrors/centos.org/7.2.1511/extras/x86_64'
'rpm' 'Kibana repository for 4.4.x packages x86_64' 'kibana-4.4' '99' 'http://packages.elastic.co/kibana/4.4/centos'
'rpm' 'Logstash repository for 2.1 packages x86_64' 'logstash-2.1' '99' 'http://packages.elasticsearch.org/logstash/2.1/centos'
'rpm' 'nginx repo x86_64' 'nginx/x86_64' '99' 'http://nginx.org/packages/mainline/centos/7/x86_64'
'rpm' 'CentOS-7 - Updates x86_64' 'updates/7/x86_64' '99' 'http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=updates&infra=stock' 'http://ftp.arnes.si/pub/mirrors/centos.org/7.2.1511/updates/x86_64'

But "(9" and "more)" are still created as  Centos 7 base mirrors. And even if i delete them when running full report (patchman -a) server fails on mirrorlist beacuse it expetcs < tag and none is found beacuse its a list of urls. I can live with that if you're not having time to fix it, no problem at all it's just i want to help out:)

**Comment by furlongm** [comment]
Odd. It works for me on CentOS 7 using the repo you provided:

```
# yum repolist enabled --verbose 2>/dev/null | sed -e "s/:\? *([0-9]\+ more)$//g"
Loading "fastestmirror" plugin
Config time: 0.009
Yum version: 3.4.3
Loading mirror speeds from cached hostfile
 * extras: centos.mirror.serversaustralia.com.au
Setting up Package Sacks
pkgsack time: 0.013

Repo-id      : extras
Repo-name    : CentOS-7 - Extras
Repo-revision: 1464018578
Repo-updated : Mon May 23 15:50:03 2016
Repo-pkgs    : 303
Repo-size    : 800 M
Repo-mirrors : http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=extras&infra=stock
Repo-baseurl : http://centos.mirror.serversaustralia.com.au/7.2.1511/extras/x86_64/

Repo-expire  : 21,600 second(s) (last: Thu May 26 04:02:31 2016)
Repo-filename: /etc/yum.repos.d/CentOS-Base.repo```

Can you paste the output of that command?

**Comment by gasperzupancic** [comment]
# yum repolist enabled --verbose 2>/dev/null | sed -e "s/:\? *([0-9]\+ more)$//g"
Loading "fastestmirror" plugin
Loading "patchman" plugin
Config time: 0.010
Yum version: 3.4.3
Loading mirror speeds from cached hostfile
 * base: ftp.arnes.si
 * epel: mirror.23media.de
 * extras: ftp.arnes.si
 * updates: ftp.arnes.si
Setting up Package Sacks
pkgsack time: 0.013
Repo-id      : base/7/x86_64
Repo-name    : CentOS-7 - Base
Repo-revision: 1449700451
Repo-updated : Wed Dec  9 23:35:45 2015
Repo-pkgs    : 9,007
Repo-size    : 6.5 G
Repo-mirrors : http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock
Repo-baseurl : http://ftp.arnes.si/pub/mirrors/centos.org/7.2.1511/os/x86_64/ (9
             : more)
Repo-expire  : 21,600 second(s) (last: Thu May 26 11:23:56 2016)
Repo-filename: /etc/yum.repos.d/CentOS-Base.repo

Repo-id      : bintray--sbt-rpm
Repo-name    : bintray--sbt-rpm
Repo-updated : Tue Apr 26 03:39:19 2016
Repo-pkgs    : 10
Repo-size    : 9.9 M
Repo-baseurl : http://dl.bintray.com/sbt/rpm/
Repo-expire  : 21,600 second(s) (last: Thu May 26 11:23:56 2016)
Repo-filename: /etc/yum.repos.d/bintray-sbt-rpm.repo

Repo-id      : elasticsearch-2.x
Repo-name    : Elasticsearch repository for 2.x packages
Repo-revision: 1463501547
Repo-updated : Tue May 17 18:12:28 2016
Repo-pkgs    : 13
Repo-size    : 353 M
Repo-baseurl : https://packages.elastic.co/elasticsearch/2.x/centos/
Repo-expire  : 21,600 second(s) (last: Thu May 26 11:23:57 2016)
Repo-filename: /etc/yum.repos.d/elasticserach.repo

Repo-id      : epel/x86_64
Repo-name    : Extra Packages for Enterprise Linux 7 - x86_64
Repo-revision: 1464216702
Repo-tags    : binary-x86_64
Repo-updated : Thu May 26 03:05:10 2016
Repo-pkgs    : 10,055
Repo-size    : 7.8 G
Repo-metalink: https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=x86_64
  Updated    : Thu May 26 03:05:10 2016
Repo-baseurl : http://mirror.23media.de/epel/7/x86_64/
Repo-expire  : 21,600 second(s) (last: Thu May 26 11:23:58 2016)
Repo-filename: /etc/yum.repos.d/epel.repo

Repo-id      : extras/7/x86_64
Repo-name    : CentOS-7 - Extras
Repo-revision: 1464018578
Repo-updated : Mon May 23 17:50:03 2016
Repo-pkgs    : 303
Repo-size    : 800 M
Repo-mirrors : http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=extras&infra=stock
Repo-baseurl : http://ftp.arnes.si/pub/mirrors/centos.org/7.2.1511/extras/x86_64/

Repo-expire  : 21,600 second(s) (last: Thu May 26 11:23:58 2016)
Repo-filename: /etc/yum.repos.d/CentOS-Base.repo

Repo-id      : kibana-4.4
Repo-name    : Kibana repository for 4.4.x packages
Repo-revision: 1457638486
Repo-updated : Thu Mar 10 20:34:51 2016
Repo-pkgs    : 5
Repo-size    : 153 M
Repo-baseurl : http://packages.elastic.co/kibana/4.4/centos/
Repo-expire  : 21,600 second(s) (last: Thu May 26 11:23:59 2016)
Repo-filename: /etc/yum.repos.d/kibana.repo

Repo-id      : logstash-2.1
Repo-name    : Logstash repository for 2.1 packages
Repo-updated : Tue Feb 16 23:49:40 2016
Repo-pkgs    : 4
Repo-size    : 286 M
Repo-baseurl : http://packages.elasticsearch.org/logstash/2.1/centos/
Repo-expire  : 21,600 second(s) (last: Thu May 26 11:23:59 2016)
Repo-filename: /etc/yum.repos.d/logstash.repo

Repo-id      : nginx/x86_64
Repo-name    : nginx repo
Repo-revision: 1464117172
Repo-updated : Tue May 24 21:12:57 2016
Repo-pkgs    : 74
Repo-size    : 55 M
Repo-baseurl : http://nginx.org/packages/mainline/centos/7/x86_64/
Repo-expire  : 21,600 second(s) (last: Thu May 26 11:24:00 2016)
Repo-filename: /etc/yum.repos.d/nginx.repo

Repo-id      : updates/7/x86_64
Repo-name    : CentOS-7 - Updates
Repo-revision: 1463746753
Repo-updated : Fri May 20 14:22:02 2016
Repo-pkgs    : 1,676
Repo-size    : 4.6 G
Repo-mirrors : http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=updates&infra=stock
Repo-baseurl : http://ftp.arnes.si/pub/mirrors/centos.org/7.2.1511/updates/x86_64/

Repo-expire  : 21,600 second(s) (last: Thu May 26 11:24:00 2016)
Repo-filename: /etc/yum.repos.d/CentOS-Base.repo

repolist: 21,147


i re ran the client on this host and i think the problem is with first line:
'rpm' 'CentOS-7 - Base x86_64' 'base/7/x86_64' '99' 'http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock' '(9' 'more)'

are you're adding anything in ' ' as a repo? that would explain it.

this are last two entires in "mirror list" for centos 7 base

(9	0	Enabled	Yes	No	No	May 26, 2016, 4:23 p.m.	None	Delete	Edit
more)	0	Enabled	Yes	No	No	May 26, 2016, 4:23 p.m.	None	Delete	Edit

**Comment by furlongm** [comment]
Ok so it's getting it from this line:

updates: ftp.arnes.si Setting up Package Sacks pkgsack time: 0.013 Repo-id : base/7/x86_64 Repo-name : CentOS-7 - Base Repo-revision: 1449700451 Repo-updated : Wed Dec 9 23:35:45 2015 Repo-pkgs : 9,007 Repo-size : 6.5 G Repo-mirrors : http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock Repo-baseurl : http://ftp.arnes.si/pub/mirrors/centos.org/7.2.1511/os/x86_64/ (9 : more) Repo-expire : 21,600 second(s) (last: Thu May 26 11:23:56 2016) Repo-filename: /etc/yum.repos.d/CentOS-Base.repo

Does that line appear exactly like that in the output or is that a copy and paste issue? It seems like that part should should span several lines.

**Comment by furlongm** [comment]
Try the fix in 18eb44e

**Comment by gasperzupancic** [comment]
That line was copy/paste issue. For test i tried before and after fix 18eb44e and i can confirm that it is working now. No more "9 more" repos and even the line with mirrorlist is ok.

before:
Finding yum repos...
'rpm' 'CentOS-7 - Base x86_64' 'base/7/x86_64' '99' 'http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock' **'(9' 'more)'**

after fix:
Finding yum repos...
'rpm' 'CentOS-7 - Base x86_64' 'base/7/x86_64' '99' 'http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock' 'http://ftp.arnes.si/pub/mirrors/centos.org/7.2.1511/os/x86_64'


but i still got the issue with processing reports of mirrorlists. It must me something wrong on my side i guess.

**Comment by furlongm** [comment]
What is the issue with processing reports of mirrorlists?

**Comment by gasperzupancic** [comment]
When running patchman -a i still get:
lxml.etree.XMLSyntaxError: Start tag expected, '<' not found, line 1, column 1
with mirror:
Found yum rpm repo - http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=extras&infra=stock/repodata/repomd.xml.bz2

this is the mirror that is serving mirrorlist with whatever url you call it.

**Comment by gasperzupancic** [comment]
sorry again. it looks like it was some leftover from before. I cleaned the repos and mirrors and started again, and for now it looks ok!

thanks again for all your help and i have to say, you're doing a great job!

**Comment by furlongm** [comment]
Thanks! :)

**Comment by gasperzupancic** [comment]
ok. now the reports are finished and the thing that bothered me before (i was checking output of process and dashboard) is that on the dashboard i  get info about "1 Repositories have some mirrors that are failing" and when i check the repo there is a mirrorlist with 0 pacakages. This is probably just a check if there are 0 packages than something is wrong? It doesnt includes that mirrorlist does not have any packages?

**Comment by furlongm** [comment]
Is the mirrorlist the repo that is failing? I can't reproduce it.

**Comment by gasperzupancic** [comment]
Sorry to reopen thi again. But over the weekend my host with mirrorlist reported back and after running patchman -a, process fails again. I've managed to figured it out. I've deleted the mirrors and later noticed that it had mirrorlist flag missing. Is it possible to auto check mirrorlist if its found?

**Comment by gasperzupancic** [comment]
and about that issue that was bothering me about mirrolist package count:
![image](https://cloud.githubusercontent.com/assets/2493125/15645752/9c083c5c-265a-11e6-9db7-864c4b18e90b.png)

this is producing warning on "dashboard":)

**Comment by furlongm** [comment]
The problem is in the "Last Access" column, not the "Packages" column. It looks like something went wrong when accessing that url.

Also, a mirrorlist should be automatically detected as a mirrorlist. If this is not happening, can you let me know the url that is failing?

**Comment by gasperzupancic** [comment]
hehe, still the same famous

http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock
http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=extras&infra=stock
http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=updates&infra=stock

**Comment by furlongm** [comment]
Ok, so if I use one of those, it works for me:

```
~/src/patchman> PYTHONPATH=. sbin/patchman -R 29 -r
Refreshing metadata for repo 29
test
Found mirrorlist - http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=extras&infra=stock/repodata/repomd.xml.bz2
Added mirror - http://ftp.swin.edu.au/centos/7.2.1511/extras/x86_64/
Added mirror - http://mirror.internode.on.net/pub/centos/7.2.1511/extras/x86_64/
Added mirror - http://centos.uberglobalmirror.com/7.2.1511/extras/x86_64/
Added mirror - http://mirror.optus.net/centos/7.2.1511/extras/x86_64/
Added mirror - http://centos.mirror.serversaustralia.com.au/7.2.1511/extras/x86_64/
5 mirrors already exist, not adding http://mirror.aarnet.edu.au/pub/centos/7.2.1511/extras/x86_64/
5 mirrors already exist, not adding http://centos.mirror.digitalpacific.com.au/7.2.1511/extras/x86_64/
5 mirrors already exist, not adding http://mirror.ventraip.net.au/CentOS/7.2.1511/extras/x86_64/
5 mirrors already exist, not adding http://centos.mirror.crucial.com.au/7.2.1511/extras/x86_64/
5 mirrors already exist, not adding http://mirror.colocity.com/centos/7.2.1511/extras/x86_64/
http://ftp.swin.edu.au/centos/7.2.1511/extras/x86_64/repodata/repomd.xml.bz2 - Not Found
http://ftp.swin.edu.au/centos/7.2.1511/extras/x86_64/repodata/repomd.xml.gz - Not Found
Downloading repo info (1/2):       100%|#########################################################################################################################################################################################################################|Time: 0:00:00
Found yum rpm repo - http://ftp.swin.edu.au/centos/7.2.1511/extras/x86_64/repodata/repomd.xml
Downloading repo info (2/2):       100%|#########################################################################################################################################################################################################################|Time: 0:00:00
Extracting packages:               100%|#########################################################################################################################################################################################################################|Time: 0:00:00
Adding 305 new packages:           100%|#########################################################################################################################################################################################################################|Time: 0:00:00
http://mirror.internode.on.net/pub/centos/7.2.1511/extras/x86_64/repodata/repomd.xml.bz2 - Not Found
http://mirror.internode.on.net/pub/centos/7.2.1511/extras/x86_64/repodata/repomd.xml.gz - Not Found
Downloading repo info (1/2):       100%|#########################################################################################################################################################################################################################|Time: 0:00:00
Found yum rpm repo - http://mirror.internode.on.net/pub/centos/7.2.1511/extras/x86_64/repodata/repomd.xml
Downloading repo info (2/2):       100%|#########################################################################################################################################################################################################################|Time: 0:00:00
Extracting packages:               100%|#########################################################################################################################################################################################################################|Time: 0:00:00
Adding 305 new packages:           100%|#########################################################################################################################################################################################################################|Time: 0:00:00
http://centos.uberglobalmirror.com/7.2.1511/extras/x86_64/repodata/repomd.xml.bz2 - Not Found
http://centos.uberglobalmirror.com/7.2.1511/extras/x86_64/repodata/repomd.xml.gz - Not Found
Downloading repo info (1/2):       100%|#########################################################################################################################################################################################################################|Time: 0:00:00
Found yum rpm repo - http://centos.uberglobalmirror.com/7.2.1511/extras/x86_64/repodata/repomd.xml
Downloading repo info (2/2):       100%|#########################################################################################################################################################################################################################|Time: 0:00:00
Extracting packages:               100%|#########################################################################################################################################################################################################################|Time: 0:00:00
Adding 305 new packages:           100%|#########################################################################################################################################################################################################################|Time: 0:00:00
http://mirror.optus.net/centos/7.2.1511/extras/x86_64/repodata/repomd.xml.bz2 - Not Found
http://mirror.optus.net/centos/7.2.1511/extras/x86_64/repodata/repomd.xml.gz - Not Found
Downloading repo info (1/2):       100%|#########################################################################################################################################################################################################################|Time: 0:00:00
Found yum rpm repo - http://mirror.optus.net/centos/7.2.1511/extras/x86_64/repodata/repomd.xml
Downloading repo info (2/2):       100%|#########################################################################################################################################################################################################################|Time: 0:00:00
Extracting packages:               100%|#########################################################################################################################################################################################################################|Time: 0:00:00
Adding 305 new packages:           100%|#########################################################################################################################################################################################################################|Time: 0:00:00
http://centos.mirror.serversaustralia.com.au/7.2.1511/extras/x86_64/repodata/repomd.xml.bz2 - Not Found
http://centos.mirror.serversaustralia.com.au/7.2.1511/extras/x86_64/repodata/repomd.xml.gz - Not Found
Downloading repo info (1/2):       100%|#########################################################################################################################################################################################################################|Time: 0:00:00
Found yum rpm repo - http://centos.mirror.serversaustralia.com.au/7.2.1511/extras/x86_64/repodata/repomd.xml
Downloading repo info (2/2):       100%|#########################################################################################################################################################################################################################|Time: 0:00:00
Extracting packages:               100%|#########################################################################################################################################################################################################################|Time: 0:00:00
Adding 305 new packages:           100%|#########################################################################################################################################################################################################################|Time: 0:00:00
```

What output do you see?

**Comment by gasperzupancic** [comment]
Well i kinda feel awkward now. I've deleted all mirrors/repos and re run patchman-client on host with mirrorlist. I have also installed celery for auto process reports and the first thing is that mirrorlist is not properly detected and now when i re run patchman -a the process fails beacuse mirrorlist is not a repo. When i manualy put the checkmark on mirrorlist process runs through but  then i'm back on the same "picture" as above.
Maybe it is a feature and i don't understand it properly. I'll try to "wipe" the db and start over. Maybe there is an issue with that. I'll report back.

**Comment by furlongm** [comment]
Ok, let's re-open the issue. I can't reproduce it so you may need to do a little debugging. It seems like there may be a bug in the mirrorlist detection code and it's not something that I've come across before.

To start with, what is the output of the command `patchman -R 29 -r` where 29 is the ID of your repo (run `patchman -lr` to get the repo IDs).

**Comment by gasperzupancic** [comment]
Ok, now i've dumped the db and started fresh. Dropped the db and created new, run syncdb and opened fresh and empty dashboard. I've run patchman-client report only on a server with mirrorlist  and first thing i noticed is that mirrorlist is not detected also runing -a option fails then.
When i manualy enabled mirrorlist checkmark on mirrorlists then reports run through. 
os: # cat /etc/redhat-release
CentOS Linux release 7.2.1511 (Core)
mysql: # mysql -V
mysql  Ver 15.1 Distrib 5.5.47-MariaDB, for Linux (x86_64) using readline 5.1
python: # python --version
Python 2.7.5
my install dir is /opt/patchman

1. # sbin/patchman -lr
Printing information for all repos
10 : CentOS-7 - Base x86_64
security: False  arch: x86_64
Mirrors:
 17 : http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock
 last updated: 2016-05-31 08:20:33    checksum: None
 18 : http://ftp.arnes.si/pub/mirrors/centos.org/7.2.1511/os/x86_64
 last updated: 2016-05-31 08:20:33    checksum: None

11 : bintray--sbt-rpm x86_64
security: False  arch: x86_64
Mirrors:
 19 : http://dl.bintray.com/sbt/rpm
 last updated: 2016-05-31 08:20:33    checksum: None

12 : Elasticsearch repository for 2.x packages x86_64
security: False  arch: x86_64
Mirrors:
 20 : https://packages.elastic.co/elasticsearch/2.x/centos
 last updated: 2016-05-31 08:20:33    checksum: None

13 : Extra Packages for Enterprise Linux 7 - x86_64 x86_64
security: False  arch: x86_64
Mirrors:
 21 : http://mirror.23media.de/epel/7/x86_64
 last updated: 2016-05-31 08:20:33    checksum: None

14 : CentOS-7 - Extras x86_64
security: False  arch: x86_64
Mirrors:
 22 : http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=extras&infra=stock
 last updated: 2016-05-31 08:20:33    checksum: None
 23 : http://ftp.arnes.si/pub/mirrors/centos.org/7.2.1511/extras/x86_64
 last updated: 2016-05-31 08:20:33    checksum: None

15 : Kibana repository for 4.4.x packages x86_64
security: False  arch: x86_64
Mirrors:
 24 : http://packages.elastic.co/kibana/4.4/centos
 last updated: 2016-05-31 08:20:33    checksum: None

16 : Logstash repository for 2.1 packages x86_64
security: False  arch: x86_64
Mirrors:
 25 : http://packages.elasticsearch.org/logstash/2.1/centos
 last updated: 2016-05-31 08:20:33    checksum: None

17 : nginx repo x86_64
security: False  arch: x86_64
Mirrors:
 26 : http://nginx.org/packages/mainline/centos/7/x86_64
 last updated: 2016-05-31 08:20:33    checksum: None

18 : CentOS-7 - Updates x86_64
security: False  arch: x86_64
Mirrors:
 27 : http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=updates&infra=stock
 last updated: 2016-05-31 08:20:33    checksum: None
 28 : http://ftp.arnes.si/pub/mirrors/centos.org/7.2.1511/updates/x86_64
 last updated: 2016-05-31 08:20:33    checksum: None

2. # sbin/patchman -R 10 -r
Refreshing metadata for repo 10
CentOS-7 - Base x86_64
Found mirrorlist - http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock
Added mirror - http://mirror.lihnidos.org/CentOS/7.2.1511/os/x86_64/
Added mirror - http://mirrors.xgroup.si/CentOS/7.2.1511/os/x86_64/
Added mirror - http://ftp.arnes.si/pub/mirrors/centos.org/7.2.1511/os/x86_64/
5 mirrors already exist, not adding http://centos.t-2.net/7.2.1511/os/x86_64/
5 mirrors already exist, not adding http://mirrors.prometeus.net/centos/7.2.1511/os/x86_64/
5 mirrors already exist, not adding http://ba.mirror.garr.it/mirrors/CentOS/7.2.1511/os/x86_64/
5 mirrors already exist, not adding http://mirror.crazynetwork.it/centos/7.2.1511/os/x86_64/
5 mirrors already exist, not adding http://mi.mirror.garr.it/mirrors/CentOS/7.2.1511/os/x86_64/
5 mirrors already exist, not adding ftp://ftp.eutelia.it/CentOS/7.2.1511/os/x86_64/
5 mirrors already exist, not adding http://centos.fastbull.org/centos/7.2.1511/os/x86_64/
Unknown error: http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock/repodata/repomd.xml.bz2 - timed out
Found yum rpm repo - http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock/repodata/repomd.xml.gz
Traceback (most recent call last):
  File "sbin/patchman", line 603, in <module>
    main()
  File "sbin/patchman", line 597, in main
    showhelp = process_args(args)
  File "sbin/patchman", line 569, in process_args
    refresh_repos(args.repo, args.force)
  File "sbin/patchman", line 112, in refresh_repos
    repo.refresh(force)
  File "/usr/lib/python2.7/site-packages/patchman-0.9.4-py2.7.egg/patchman/repos/models.py", line 84, in refresh
    refresh_rpm_repo(self)
  File "/usr/lib/python2.7/site-packages/patchman-0.9.4-py2.7.egg/patchman/repos/utils.py", line 534, in refresh_rpm_repo
    refresh_yum_repo(mirror, data, repo_url, ts)
  File "/usr/lib/python2.7/site-packages/patchman-0.9.4-py2.7.egg/patchman/repos/utils.py", line 419, in refresh_yum_repo
    primary_url, checksum, checksum_type = get_primary_url(repo_url, data)
  File "/usr/lib/python2.7/site-packages/patchman-0.9.4-py2.7.egg/patchman/repos/utils.py", line 172, in get_primary_url
    context = etree.parse(StringIO(data), etree.XMLParser())
  File "lxml.etree.pyx", line 3197, in lxml.etree.parse (src/lxml/lxml.etree.c:64816)
  File "parser.pxi", line 1588, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:92901)
  File "parser.pxi", line 1617, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:93194)
  File "parser.pxi", line 1495, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:92003)
  File "parser.pxi", line 1011, in lxml.etree._BaseParser._parseDoc (src/lxml/lxml.etree.c:88660)
  File "parser.pxi", line 577, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:84385)
  File "parser.pxi", line 676, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:85488)
  File "parser.pxi", line 616, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:84811)
lxml.etree.XMLSyntaxError: Start tag expected, '<' not found, line 1, column 1

so i guess mirrorlist is not detected? It must be something wrong with my setup?

**Comment by furlongm** [comment]
Looks like the error is here:

```
Unknown error: http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock/repodata/repomd.xml.bz2 - timed out
```

So it times out.

Can you add a few print statements (`print e.__dict__` or `print e`) and raise an exception in get_url in `patchman/repos/utils.py` when e == "timed out"? That way we can see where it's being called from and how to handle it.

Also, it shouldn't be adding `repodata/repomd.xml.bz2` to the end of the url. So it looks like it's not marking it as a mirrorlist. Are you running the latest version from git with all the bugfixes? Might need to add some print statements to `mirrorlist_check` as well to see why that doesn't work.

**Comment by gasperzupancic** [comment]
yes, im running latest version from your git. i'll try to put some print statements as you suggested and ill report back.

**Comment by gasperzupancic** [comment]
my python knowledge is limited, so i couldnt get that print exceptions to run. I've managed to get to the point that this url is a mirrorlist. It proprely adds all mirrors inside but that part of code doesnt seem to work: (?) in utils.py / mirrorlists_check(repo) function
mirror.mirrorlist = True
mirror.last_access_ok = True
mirror.save()

**Comment by gasperzupancic** [comment]
This was my bad. I had obviously pip installed patchman and i was running from wrong path. After you figured it out i started:
PYTHONPATH=.  sbin/patchman -r -R 145 

..SUCCESS:) thanks for all the help!
