### ISSUE TITLE
improvement: marking repository as security enabled/disabled page refreshing

### ISSUE THREAD

**Issue by gasperzupancic** [furlongm/patchman#18]
i noticed that if i click on the button to  mark repository as security sometimes refreshes the page and clears search filter and sometimes it just marks the and you can edit others.

The thing is, if you click on the button in the middle (red or green icon inside) its ok. But if you click anywhere else on the button it refreshes the page and clears filter. Is this a feature or can it be "fixed" so that if you click anywhere on the button it stays on the page?

edit:
that is from the chrome browser. In firefox this feature doesn't seem to work at all. if you click on a button you get a refresh and button doesnt reflect the change.

**Comment by furlongm** [comment]
I've been working on moving the codebase to use django-bootstrap3. Hopefully that work will fix this issue.

**Comment by furlongm** [comment]
Fixed in 11dfbab.
