### ISSUE TITLE
Automate createsuperuser

### ISSUE THREAD

**Issue by dandunckelman** [furlongm/patchman#181]
I'd like to allow Puppet to setup my server automatically.

To do this, I need to automate `patchman-manage createsuperuser` with the user's password.

I can't find a way around the prompts.
- I tried `echo MYpassword | patchman-manage createsuperuser --username myusername --email myusername@example.com`
  - That ended up not setting the password, so I was getting this:
    - `TypeError: create_superuser() takes exactly 4 arguments (3 given)`
- I also tried setting ENV vars as described [here](https://docs.djangoproject.com/en/3.0/ref/django-admin/#createsuperuser)

If this is by design and won't be allowed, then I'll happily close the issue and live with the manual step.

Thanks.

**Comment by furlongm** [comment]
You can use fixtures to do that:

https://stackoverflow.com/questions/8017204/users-in-initial-data-fixture

**Comment by dandunckelman** [comment]
Nice! Thanks!
