### ISSUE TITLE
"POST /reports/upload/ HTTP/1.1" 404

### ISSUE THREAD

**Issue by stlinux** [furlongm/patchman#189]
Hello, I followed the installation step by step but I cannot upload reports from my clients, I am running it in centos7 with httpd.
This is the error and is this the default?

"POST /reports/upload/ HTTP/1.1" 404

{code}
[root@node01 conf.d]# pwd
/etc/httpd/conf.d
[root@node01 conf.d]# cat patchman.conf 
Define patchman_pythonpath /usr/lib/python2.7/site-packages
WSGIScriptAlias /patchman ${patchman_pythonpath}/patchman/wsgi.py
WSGIPythonPath ${patchman_pythonpath}

<Directory ${patchman_pythonpath}>
    <Files wsgi.py>
        Require all granted
    </Files>
    AllowOverride All
</Directory>

Alias /patchman/static "/var/lib/patchman/static"
<Location /patchman/static>
    SetHandler None
</Location>

<Directory /var/lib/patchman/static>
    Require all granted
</Directory>

<Location /patchman/reports/upload>
    # Add the IP addresses of your client networks/hosts here
    # to allow uploading of reports
    Require ip 127.0.0.0/255.0.0.0
    Require ip 10.64.7.9/24
    Require ip ::1/128
</Location>
[root@node01 conf.d]# 

{code}

Thank you very much, I await your coementaries

**Comment by furlongm** [comment]
It should be `POST patchman/reports/upload/` ? Is the path set correctly on the client?

**Comment by stlinux** [comment]
Indeed, the problem was that the path was not correctly indicated.

Thank you very much, if you want you can close the issue
