### ISSUE TITLE
problem with editing repo/mirror when clicking on checksum id on dashboard page

### ISSUE THREAD

**Issue by gasperzupancic** [furlongm/patchman#19]
![image](https://cloud.githubusercontent.com/assets/2493125/15646380/923750de-265d-11e6-8faa-51b9362e6722.png)

when clicking on any repo marked on the picture i get an error:

TemplateSyntaxError at /repos/mirrors/
Could not parse the remainder: '/mirror_edit_repo.html' from 'repos/mirror_edit_repo.html'
Request Method:	GET
Request URL:	http://patchman.ts.telekom.si/patchman/repos/mirrors/?checksum=77b026cbc7fb74e36a8137874cc59244bfc8f075
Django Version:	1.8.12
Exception Type:	TemplateSyntaxError
Exception Value:	
Could not parse the remainder: '/mirror_edit_repo.html' from 'repos/mirror_edit_repo.html'
Exception Location:	/usr/lib64/python2.7/site-packages/django/template/base.py in __init__, line 640
Python Executable:	/usr/bin/python
Python Version:	2.7.5
Python Path:	
['/opt/patchman',
 '/opt/patchman_new/patchman',
 '/usr/lib/python2.7/site-packages/patchman-0.9.4-py2.7.egg',
 '/usr/lib64/python27.zip',
 '/usr/lib64/python2.7',
 '/usr/lib64/python2.7/plat-linux2',
 '/usr/lib64/python2.7/lib-tk',
 '/usr/lib64/python2.7/lib-old',
 '/usr/lib64/python2.7/lib-dynload',
 '/usr/lib64/python2.7/site-packages',
 '/usr/lib64/python2.7/site-packages/gtk-2.0',
 '/usr/lib/python2.7/site-packages']
Server time:	Mon, 30 May 2016 11:55:33 +0200

**Comment by furlongm** [comment]
I've already fixed this as part of a bigger commit that i'll push soon, but you can fix it locally by changing `{% gen_table page.object_list repos/mirror_edit_repo.html %}` to `{% gen_table page.object_list 'repos/mirror_edit_repo.html' %}` in patchman/repos/templates/repos/mirror_with_repo_list.html

**Comment by gasperzupancic** [comment]
ok:) tnx for the input.!
