### ISSUE TITLE
enable HTTPS

### ISSUE THREAD

**Issue by karkaaa** [furlongm/patchman#196]
Hi,

How i can enable HTTPS on patchman?

Thank you.

**Comment by CosaNostrack** [comment]
> 
> 
> Hi,
> 
> How i can enable HTTPS on patchman?
> 
> Thank you.

Hey friend,

I was wondering the same.
Find out you can enable HTTPS without any problem, you just have to know that the default Django/Python development web server won't support it.

So you have to run Patchman through an Apache server, then enable HTTPS/SSL on it (many tutorials are available).

If you look on patchman-client's source code, you'll see that comments are mentioning https, so I guess the client will work as well with an HTTPS server.
Didn't test yet, but I don't see why it wouldn't work.

Hope it helps

**Comment by soumplis** [comment]
We are running patchman behind an SSL proxy and clients have no problem communicating.

**Comment by furlongm** [comment]
The answer provided by @CosaNostrack is correct, closing.
