### ISSUE TITLE
Installation on Ubuntu 20.04

### ISSUE THREAD

**Issue by ForelliCH** [furlongm/patchman#199]
Can Patchman be configured on Ubuntu 20.04? ..sorry to ask a few hours after the release. But we just received this request today.

**Comment by Fossil01** [comment]
I second the need for a 20.04 repo.

**Comment by furlongm** [comment]
This is coming soon. There are a few more pieces to finish first. In the meantime, you can try the `develop` branch which should work on focal.

**Comment by Chup4Chups** [comment]
Any update regarding 20.04 support ?

**Comment by furlongm** [comment]
Still a work in progress unfortunately. Just pushed an updated version to the `develop` branch, if anyone is interested in testing.

**Comment by EvilBMP** [comment]
Any news on this? 

I've seen, that in the develop branch the version was bumped to v2. Do you plan to release v2 in 2021?

**Comment by furlongm** [comment]
The v2 packages and installation instructions are now released :-) Let me know if you have any issues.
