### ISSUE TITLE
request: security updates report for CentOS

### ISSUE THREAD

**Issue by gasperzupancic** [furlongm/patchman#20]
it would be very nice to have the same feature as debian/ubuntu overview with security updates "needed".

**Comment by furlongm** [comment]
For future reference:

Normally for CentOS the patchman server will check the upsteam repos and patchman will calculate what package updates are needed (without asking the host what update it *thinks* are needed). Sometimes this can highlight where repos are broken on the hosts (e.g. if patchman and the host report different updates). In patchman you mark the update repo as a security repo and all packages will be marked as security updates.

While this works well for Debian/Ubuntu (as there are separate bugfix and security repos), it doesn't work so well for Red Hat / CentOS. It marks *all* updates from the update repo as security updates.

For RHEL, we can't connect to the upstream subscription-manager server without authenticating, so patchman can only collect the updates from the host for those repos. It cannot calculate the updates using only the repos. The benefit of this is that you get more detailed information regarding security vs bugfix updates.

It looks like the errata at http://cefs.steve-meier.de/ can be used to add this feature.

**Comment by gasperzupancic** [comment]
what about
https://github.com/wied03/centos-package-cron ?

**Comment by furlongm** [comment]
For CentOS hosts, you could see if running that on the host works (in addition to collecting updates from the hosts). That would solve it client-side and give people an option.

It uses the same upstream site ( http://cefs.steve-meier.de/ ) that I was going to use for server-side processing, so in theory they should match.

**Comment by gasperzupancic** [comment]
Yes that is what i was aiming to (the same upstream site). Was just trying to help out:) I though maybe you could "merge" that into the server side feeding it with repos and cross matching afterwards with package list. But on the other side you probably can do the same without extra step with this tool.

**Comment by furlongm** [comment]
Can you checkout a13f765ec5d62423f51806e00943e387a5576399 and see if this commit fixes your issue? You may need to follow the instructions in the UPGRADE file to run the migrations after checking out the branch.

**Comment by gasperzupancic** [comment]
hey,

it looks ok for now. After the checkout upgrade procedure wasn't needed altough i followed your instructions.  Thanks again for doing a great job!
