### ISSUE TITLE
 change text  --- "Patch Management Dashboard for example.com"---

### ISSUE THREAD

**Issue by stlinux** [furlongm/patchman#204]
Hello, I need to remove this message and show a personalized one.
---
Patch Management Dashboard for example.com
---
I would appreciate help to understand what I have to configure.

Thank you very much, regards.

Norman.

**Comment by furlongm** [comment]
If you go into the admin section, you can change the site name from `example.com` to whatever you want.

**Comment by stlinux** [comment]
Brilliant.

I modified it based on your comment and it worked correctly.

Thank you.

**Comment by skatsaounis** [comment]
@stlinux  Hi, in case of caching (eg. memcache) you may need to clear cache as well to make it work:

```python
# python3 manage.py shell
from django.contrib.sites.models import Site
from django.conf import settings
Site.objects.filter(pk=settings.SITE_ID).update(
    name='my_awesome_site_name', domain='my_awesome_site_name_domain')
Site.objects.clear_cache()
```

**Comment by skatsaounis** [comment]
In our Patchman installation we have created management commands and this one is done by simply running: `python manage.py set_site --name my_awesome_site_name --clear-cache`.

If @furlongm is going to accept #194 this command will be available to upstream as well.
