### ISSUE TITLE
 Allow all hosts uplod report  | Require ip xxx / xxx | patchman.conf

### ISSUE THREAD

**Issue by stlinux** [furlongm/patchman#205]
Hello, please could you tell me how I can do so that I don't have to indicate the ip / mask of the hosts that allow me to upload the report in patchman.conf. 
Require ip xxx / xxx
 In summary, I don't want to restrict the upload, I want all those hosts where I have the client and the client configuration installed to do so. Thank you in advance for all your work and collaboration. 
I send you a hug. 
Norman.

**Comment by furlongm** [comment]
`Require ip 0.0.0.0` should allow all IPs
