### ISSUE TITLE
patchman client broken on ubuntu 16.04

### ISSUE THREAD

**Issue by furlongm** [furlongm/patchman#21]
Looks like it's missing a '/'.

@gasperzupancic did you have a fix for this already?

**Comment by gasperzupancic** [comment]
I think I do, but this is not ideal solution i guess. I've added extra '/' into the regex in the client.
For some time i was messing around with detecting ubuntu version but given up on the idea. 

In our environment we're using ansible so we're pushing 3 different "patchman client's" for ubuntu (10, 14, 16) so we're covered in a way.

**Comment by furlongm** [comment]
The fix for 16.04 breaks 14.04 and 10.04?

**Comment by furlongm** [comment]
Should be fixed in 4c23a07. Tested on 16.04 and 14.04.
