### ISSUE TITLE
enhancement: Change color of date on dashboard if host didnt report back in X days

### ISSUE THREAD

**Issue by gasperzupancic** [furlongm/patchman#22]
#It would be a neat feature to see if a host didn't report back in some days. It could be a nice thing to have to quickly overview stale reports or there is something wrong with client on host or network issue etc...

**Comment by furlongm** [comment]
![image](https://cloud.githubusercontent.com/assets/114803/16493207/01d94d6a-3f28-11e6-87eb-e9739d83002e.png)

The dashboard currently has this functionality (see image), with a default of 14 days.
