### ISSUE TITLE
patchman-client not working

### ISSUE THREAD

**Issue by jaydeepjc** [furlongm/patchman#227]
On Client Side (CentOS 7 server)
Installed Client via `yum install -y patchman-client`

It completed without any issue.

Then to add that client on patchman server we hit below command on client

`patchman-client -s https://192.168.0.121/patchman/`

But it didn't give any output nor we can see it added on patchman server

Could you let us know proper steps to configure client

**Comment by furlongm** [comment]
Can you try with `-v -d` flags for verbose and debug?

**Comment by jaydeepjc** [comment]
`patchman-client -s https://192.168.0.121/patchman/ -v -d
Attempting to obtain lock: /var/lock/patchman/patchman.lock
Patchman configuration seems OK: ${conf}
Patchman Server: https://192.168.0.121/patchman/
Tags: Server
Report: 0
FQDN:   devserver.mycomp.net
Kernel: 3.10.0-1127.13.1.el7.x86_64
Arch:   x86_64
OS:     CentOS Linux release 7.8.2003 (Core)
Finding installed rpms...
'puppetlabs-release' '' '22.0' '2' 'noarch' 'rpm'
'nagios-plugins-by_ssh' '' '2.3.3' '2.el7' 'x86_64' 'rpm'
'traceroute' '3' '2.0.22' '2.el7' 'x86_64' 'rpm'
'javapackages-tools' '' '3.4.1' '11.el7' 'noarch' 'rpm'
'nagios-plugins-sensors' '' '2.3.3' '2.el7' 'x86_64' 'rpm'
'perl-HTTP-Daemon' '' '6.01' '8.el7' 'noarch' 'rpm'
...
...
...
...
...
'curl' '' '7.29.0' '57.el7' 'x86_64' 'rpm'
'nagios-plugins-mysql' '' '2.3.3' '2.el7' 'x86_64' 'rpm'
'nagios-plugins-fping' '' '2.3.3' '2.el7' 'x86_64' 'rpm'
'vim-minimal' '2' '7.4.629' '6.el7' 'x86_64' 'rpm'
'libnetfilter_conntrack' '' '1.0.6' '1.el7_3' 'x86_64' 'rpm'
'nagios-plugins-mrtgtraf' '' '2.3.3' '2.el7' 'x86_64' 'rpm'
Finding yum repos...
'rpm' 'CentOS-7 - Base x86_64' 'base/7/x86_64' '99' 'http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=genclo' 'http://d36uatko69830t.cloudfront.net/centos/7/os/x86_64'
'rpm' 'Extra Packages for Enterprise Linux 7 - x86_64 x86_64' 'epel/x86_64' '99' 'https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=x86_64&infra=genclo&content=centos' 'https://mirror.umd.edu/fedora/epel/7/x86_64'
'rpm' 'CentOS-7 - Extras x86_64' 'extras/7/x86_64' '99' 'http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=extras&infra=genclo' 'http://d36uatko69830t.cloudfront.net/centos/7/extras/x86_64'
'rpm' 'openbytes x86_64' 'openbytes' '99' 'https://repo.openbytes.ie/yum'
'rpm' 'CentOS-7 - Updates x86_64' 'updates/7/x86_64' '99' 'http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=updates&infra=genclo' 'http://d36uatko69830t.cloudfront.net/centos/7/updates/x86_64'
Sending data to https://192.168.0.121/patchman/ with curl:
curl --insecure --connect-timeout 60 --max-time 300 -F verbose="1" -F debug="1" -F host="devserver.mycomp.net" -F tags="Server" -F kernel="3.10.0-1127.13.1.el7.x86_64" -F arch="x86_64" -F protocol="1" -F os="CentOS Linux release 7.8.2003 (Core)" -F report="0" -F packages=\</tmp/tmp.y6xQbn299b -F repos=\</tmp/tmp.9t7VqSC011 -F sec_updates=\</tmp/tmp.qy2JWKM5zG -F bug_updates=\</tmp/tmp.raVrOSlAwx -F reboot="ServerCheck" https://192.168.0.121/patchman//reports/upload/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0 37742  100   226    0     0   1617      0 --:--:-- --:--:-- --:--:--  1637
Debug: not deleting /tmp/tmp.y6xQbn299b (packages)
Debug: not deleting /tmp/tmp.9t7VqSC011 (repos)
Debug: not deleting /tmp/tmp.qy2JWKM5zG (security updates)
Debug: not deleting /tmp/tmp.raVrOSlAwx (updates)
`

However I am still not able to see this host on patchman server

**Comment by furlongm** [comment]
Are there any indication of errors in the web server error logs?

Could you also try with removing the trailing slash from the url in `-s`?

**Comment by jaydeepjc** [comment]
I tried with `patchman-client -s https://192.168.0.121/patchman -v -d` but no luck
Not seeing any error on web server as well.

however found below , this this can help to troublshoot

` patchman-client -s https://192.168.0.121/patchman -r
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /patchman/reports/upload/
on this server.</p>
</body></html>
`

**Comment by furlongm** [comment]
You probably need to configure the IP ranges that are allowed in the apache configuration. See https://github.com/furlongm/patchman/blob/master/INSTALL.md#apache

**Comment by jaydeepjc** [comment]
I followed below method to install patchman


cat <<EOF >> /etc/yum.repos.d/openbytes.repo
[openbytes]
name=openbytes
baseurl=https://repo.openbytes.ie/yum
enabled=1
gpgcheck=0
EOF
yum install -y epel-release
yum makecache
yum install -y patchman patchman-client
systemctl restart httpd
patchman-manage createsuperuser



Still do I need to follow below steps?

chown -R :www-data /etc/patchman
chmod -R g+r /etc/patchman
chown -R :www-data /var/lib/patchman
chmod -R g+w /var/lib/patchman/db

**Comment by jaydeepjc** [comment]
You were right, Added to apache.conf file.
Now can see in reports.

**Comment by furlongm** [comment]
If you are not using celery for asynchronous processing (see INSTALL doc for details), then you need to process the report manually, either via the web interface, or with `patchman -p` on the box (see INSTALL doc for cronjob details).

**Comment by jaydeepjc** [comment]
Yeah, Got it.
Thanks a Lot for Help and Apologies for delayed reply.
