### ISSUE TITLE
Move from python 2.7 to 3.x

### ISSUE THREAD

**Issue by metalcated** [furlongm/patchman#231]
With the EOL of Python 2.7 coming in 2021, it would be recommended to move any 2.7 code to 3.x. 

Thanks

**Comment by furlongm** [comment]
The `develop` branch has changes for python3 and django 2.2 support. Specifically 167e88351e7b13f9c6a355e0413dff0df037849a addresses both issues.

**Comment by metalcated** [comment]
Haha I keep opening these and you have already thought it through ;) Good stuff.
