### ISSUE TITLE
supported Debian versions?

### ISSUE THREAD

**Issue by lanmand** [furlongm/patchman#236]
Great piece of software!
Was trying to install the .deb package on Debian 6.0 squeeze with no luck.
Wich versions of Debian are supported?

**Comment by lanmand** [comment]
Solved the problem with a workaround.
Downloaded the patchman-client.sh and run that on the < debian 6 machines
instead of installing the .deb client package.

**Comment by furlongm** [comment]
Sorry, I didn't see this previously. What was the error you got trying to install the deb?

**Comment by lanmand** [comment]
It was an error with the key-server for the repo.
And it was related to my apt proxy configuration.
so it might not be an issu after all.
Do you want me to test the installation on debian <=6 to confirm?
