### ISSUE TITLE
Add Optional argument "-h" or "-H" to pass customize host name in the patchman-client script.

### ISSUE THREAD

**Issue by srinivasrao0192** [furlongm/patchman#238]
We have some services running in GKE, Pod gets a new hostname every time it got restarted. We would like to have an optional argument in the patchman-client script, so we can pass the custom hostname in such scenarios.

**Comment by furlongm** [comment]
This is a good idea - we could go further and use `/etc/machine-id` to distinguish between different machines, rather than relying on hostname as the unique identifier. I would probably target v2 for this feature as it would require a schema change.

**Comment by macrotex** [comment]
We run patchman in a Kubernetes Pod that restarts every night getting a different random hostname. Being able to specify the hostname via an option would be very helpful.

**Comment by furlongm** [comment]
What does the pod definition look like? Is it a daemonset?

**Comment by macrotex** [comment]
We run the patchman client as a separate script in the main container. The Pod is running in a Deployment.
