### ISSUE TITLE
Not able to see pending Updates on Dashboard

### ISSUE THREAD

**Issue by jaydeepjc** [furlongm/patchman#239]
Hi,

We have installed patchman and configure clients as well however getting Error while sending reports to server and and didnt get pending updates count on Dashboard and hosts.

Below are the details for your reference 

`
[root@serv01 patchman]#  patchman-client -r -v -d
Attempting to obtain lock: /var/lock/patchman/patchman.lock
Patchman configuration seems OK: ${conf}
Patchman Server: http://192.168.0.10/patchman
Tags: Server
Report: 1
FQDN:   ser01.mydomain.net
Kernel: 3.10.0-1127.18.2.el7.x86_64
Arch:   x86_64
OS:     CentOS Linux release 7.8.2003 (Core)
Finding installed rpms...
'net-snmp-agent-libs' '1' '5.7.2' '48.el7_8.1' 'x86_64' 'rpm'
'libgcc' '' '4.8.5' '39.el7' 'x86_64' 'rpm'
'libcom_err' '' '1.42.9' '17.el7' 'x86_64' 'rpm'
'sed' '' '4.2.2' '6.el7' 'x86_64' 'rpm'
'libsepol' '' '2.5' '10.el7' 'x86_64' 'rpm'
'nagios-plugins' '' '2.3.3' '2.el7' 'x86_64' 'rpm'
'systemd-libs' '' '219' '73.el7_8.9' 'x86_64' 'rpm'
...
...
...
Finding yum repos...
'rpm' 'CentOS-7 - Base x86_64' 'base/7/x86_64' '99' 'http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=genclo' 'http://d36uatko69830t.cloudfront.net/centos/7/os/x86_64'
'rpm' 'Docker CE Stable - x86_64 x86_64' 'docker-ce-stable/x86_64' '99' 'https://download.docker.com/linux/centos/7/x86_64/stable'
'rpm' 'Extra Packages for Enterprise Linux 7 - x86_64 x86_64' 'epel/x86_64' '99' 'https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=x86_64&infra=genclo&content=centos' 'https://dl.fedoraproject.org/pub/epel/7/x86_64'
....
.....
.....
Sending data to http://192.168.0.10/patchman with curl:
curl --insecure --connect-timeout 60 --max-time 300 -F verbose="1" -F debug="1" -F host="ser01.mydomain.net" -F tags="Server" -F kernel="3.10.0-1127.18.2.el7.x86_64" -F arch="x86_64" -F protocol="1" -F os="CentOS Linux release 7.8.2003 (Core)" -F report="1" -F packages=\</tmp/tmp.cODkZbOEb8 -F repos=\</tmp/tmp.8MRVFaL291 -F sec_updates=\</tmp/tmp.ctOPJTKbLy -F bug_updates=\</tmp/tmp.99dwqEqv4V -F reboot="ServerCheck" http://192.168.0.10/patchman/reports/upload/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 39482  100   254  100 39228    156  24146  0:00:01  0:00:01 --:--:-- 24155
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>500 - Server Error</title>
</head>
<body>
<h1>500 - Server Error</h1>
<p>There has been an error. It has been reported to the site administrators and should be fixed shortly.<p>
</body>
</html>
Debug: not deleting /tmp/tmp.cODkZbOEb8 (packages)

Debug: not deleting /tmp/tmp.8MRVFaL291 (repos)

Debug: not deleting /tmp/tmp.ctOPJTKbLy (security updates)

Debug: not deleting /tmp/tmp.99dwqEqv4V (updates)
`

When we check `/tmp/tmp.ctOPJTKbLy (security updates)` and `/tmp/tmp.99dwqEqv4V (updates)` These files are blank

![image](https://user-images.githubusercontent.com/6690868/93208156-bfd91580-f779-11ea-9af2-ad32b0306d70.png)

![image](https://user-images.githubusercontent.com/6690868/93208188-d2534f00-f779-11ea-8806-025e142095eb.png)

What can be done to fix this?

**Comment by furlongm** [comment]
Try setting DEBUG=True in `/etc/patchman/local_settings.py` and/or checking your web server error logs for details of why you are getting a 500.

**Comment by jaydeepjc** [comment]
Enabled debug True and below are the error logs on httpd

`[Wed Sep 16 03:29:50.915284 2020] [:error] [pid 4433] Internal Server Error: /patchman/reports/upload/
[Wed Sep 16 03:29:50.915334 2020] [:error] [pid 4433] Traceback (most recent call last):
[Wed Sep 16 03:29:50.915338 2020] [:error] [pid 4433]   File "/usr/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
[Wed Sep 16 03:29:50.915341 2020] [:error] [pid 4433]     response = get_response(request)
[Wed Sep 16 03:29:50.915344 2020] [:error] [pid 4433]   File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
[Wed Sep 16 03:29:50.915347 2020] [:error] [pid 4433]     response = self.process_exception_by_middleware(e, request)
[Wed Sep 16 03:29:50.915350 2020] [:error] [pid 4433]   File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
[Wed Sep 16 03:29:50.915369 2020] [:error] [pid 4433]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Wed Sep 16 03:29:50.915373 2020] [:error] [pid 4433]   File "/usr/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
[Wed Sep 16 03:29:50.915376 2020] [:error] [pid 4433]     return view_func(*args, **kwargs)
[Wed Sep 16 03:29:50.915378 2020] [:error] [pid 4433]   File "/usr/lib/python2.7/site-packages/reports/views.py", line 48, in upload
[Wed Sep 16 03:29:50.915382 2020] [:error] [pid 4433]     process_report.delay(report.id)
[Wed Sep 16 03:29:50.915385 2020] [:error] [pid 4433]   File "/usr/lib/python2.7/site-packages/celery/app/task.py", line 412, in delay
[Wed Sep 16 03:29:50.915397 2020] [:error] [pid 4433]     return self.apply_async(args, kwargs)
[Wed Sep 16 03:29:50.915419 2020] [:error] [pid 4433]   File "/usr/lib/python2.7/site-packages/celery/app/task.py", line 535, in apply_async
[Wed Sep 16 03:29:50.915437 2020] [:error] [pid 4433]     **options
[Wed Sep 16 03:29:50.915452 2020] [:error] [pid 4433]   File "/usr/lib/python2.7/site-packages/celery/app/base.py", line 737, in send_task
[Wed Sep 16 03:29:50.915507 2020] [:error] [pid 4433]     amqp.send_task_message(P, name, message, **options)
[Wed Sep 16 03:29:50.915523 2020] [:error] [pid 4433]   File "/usr/lib/python2.7/site-packages/celery/app/amqp.py", line 558, in send_task_message
[Wed Sep 16 03:29:50.915550 2020] [:error] [pid 4433]     **properties
[Wed Sep 16 03:29:50.915566 2020] [:error] [pid 4433]   File "/usr/lib/python2.7/site-packages/kombu/messaging.py", line 181, in publish
[Wed Sep 16 03:29:50.915583 2020] [:error] [pid 4433]     exchange_name, declare,
[Wed Sep 16 03:29:50.915610 2020] [:error] [pid 4433]   File "/usr/lib/python2.7/site-packages/kombu/connection.py", line 527, in _ensured
[Wed Sep 16 03:29:50.915638 2020] [:error] [pid 4433]     errback and errback(exc, 0)
[Wed Sep 16 03:29:50.915655 2020] [:error] [pid 4433]   File "/usr/lib64/python2.7/contextlib.py", line 35, in __exit__
[Wed Sep 16 03:29:50.915671 2020] [:error] [pid 4433]     self.gen.throw(type, value, traceback)
[Wed Sep 16 03:29:50.915688 2020] [:error] [pid 4433]   File "/usr/lib/python2.7/site-packages/kombu/connection.py", line 419, in _reraise_as_library_errors
[Wed Sep 16 03:29:50.915708 2020] [:error] [pid 4433]     sys.exc_info()[2])
[Wed Sep 16 03:29:50.915728 2020] [:error] [pid 4433]   File "/usr/lib/python2.7/site-packages/kombu/connection.py", line 414, in _reraise_as_library_errors
[Wed Sep 16 03:29:50.915745 2020] [:error] [pid 4433]     yield
[Wed Sep 16 03:29:50.915762 2020] [:error] [pid 4433]   File "/usr/lib/python2.7/site-packages/kombu/connection.py", line 515, in _ensured
[Wed Sep 16 03:29:50.915779 2020] [:error] [pid 4433]     reraise_as_library_errors=False,
[Wed Sep 16 03:29:50.915807 2020] [:error] [pid 4433]   File "/usr/lib/python2.7/site-packages/kombu/connection.py", line 405, in ensure_connection
[Wed Sep 16 03:29:50.915826 2020] [:error] [pid 4433]     callback)
[Wed Sep 16 03:29:50.915848 2020] [:error] [pid 4433]   File "/usr/lib/python2.7/site-packages/kombu/utils/functional.py", line 333, in retry_over_time
[Wed Sep 16 03:29:50.915866 2020] [:error] [pid 4433]     return fun(*args, **kwargs)
[Wed Sep 16 03:29:50.915889 2020] [:error] [pid 4433]   File "/usr/lib/python2.7/site-packages/kombu/connection.py", line 261, in connect
[Wed Sep 16 03:29:50.915907 2020] [:error] [pid 4433]     return self.connection
[Wed Sep 16 03:29:50.915930 2020] [:error] [pid 4433]   File "/usr/lib/python2.7/site-packages/kombu/connection.py", line 802, in connection
[Wed Sep 16 03:29:50.915948 2020] [:error] [pid 4433]     self._connection = self._establish_connection()
[Wed Sep 16 03:29:50.915969 2020] [:error] [pid 4433]   File "/usr/lib/python2.7/site-packages/kombu/connection.py", line 757, in _establish_connection
[Wed Sep 16 03:29:50.915987 2020] [:error] [pid 4433]     conn = self.transport.establish_connection()
[Wed Sep 16 03:29:50.916011 2020] [:error] [pid 4433]   File "/usr/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 130, in establish_connection
[Wed Sep 16 03:29:50.916030 2020] [:error] [pid 4433]     conn.connect()
[Wed Sep 16 03:29:50.916053 2020] [:error] [pid 4433]   File "/usr/lib/python2.7/site-packages/amqp/connection.py", line 288, in connect
[Wed Sep 16 03:29:50.916073 2020] [:error] [pid 4433]     self.drain_events(timeout=self.connect_timeout)
[Wed Sep 16 03:29:50.916096 2020] [:error] [pid 4433]   File "/usr/lib/python2.7/site-packages/amqp/connection.py", line 471, in drain_events
[Wed Sep 16 03:29:50.916114 2020] [:error] [pid 4433]     while not self.blocking_read(timeout):
[Wed Sep 16 03:29:50.916216 2020] [:error] [pid 4433]   File "/usr/lib/python2.7/site-packages/amqp/connection.py", line 476, in blocking_read
[Wed Sep 16 03:29:50.916242 2020] [:error] [pid 4433]     frame = self.transport.read_frame()
[Wed Sep 16 03:29:50.916283 2020] [:error] [pid 4433]   File "/usr/lib/python2.7/site-packages/amqp/transport.py", line 236, in read_frame
[Wed Sep 16 03:29:50.916301 2020] [:error] [pid 4433]     payload = read(size)
[Wed Sep 16 03:29:50.916325 2020] [:error] [pid 4433]   File "/usr/lib/python2.7/site-packages/amqp/transport.py", line 409, in _read
[Wed Sep 16 03:29:50.916346 2020] [:error] [pid 4433]     raise IOError('Socket closed')
[Wed Sep 16 03:29:50.916367 2020] [:error] [pid 4433] OperationalError: Socket closed
`

**Comment by jaydeepjc** [comment]
![image](https://user-images.githubusercontent.com/6690868/93308970-9626f980-f820-11ea-8de2-d4aafda4db53.png)

**Comment by jaydeepjc** [comment]
Above error solved When I added SITEID = 3 in local_setting.py

**Comment by jaydeepjc** [comment]
But for Original error getting below output in error.log

`[Wed Sep 16 04:51:33.480177 2020] [:error] [pid 1813] Internal Server Error: /patchman/reports/upload/
[Wed Sep 16 04:51:33.480215 2020] [:error] [pid 1813] Traceback (most recent call last):
[Wed Sep 16 04:51:33.480219 2020] [:error] [pid 1813]   File "/usr/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
[Wed Sep 16 04:51:33.480222 2020] [:error] [pid 1813]     response = get_response(request)
[Wed Sep 16 04:51:33.480225 2020] [:error] [pid 1813]   File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
[Wed Sep 16 04:51:33.480228 2020] [:error] [pid 1813]     response = self.process_exception_by_middleware(e, request)
[Wed Sep 16 04:51:33.480231 2020] [:error] [pid 1813]   File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
[Wed Sep 16 04:51:33.480234 2020] [:error] [pid 1813]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Wed Sep 16 04:51:33.480237 2020] [:error] [pid 1813]   File "/usr/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
[Wed Sep 16 04:51:33.480240 2020] [:error] [pid 1813]     return view_func(*args, **kwargs)
[Wed Sep 16 04:51:33.480242 2020] [:error] [pid 1813]   File "/usr/lib/python2.7/site-packages/reports/views.py", line 48, in upload
[Wed Sep 16 04:51:33.480245 2020] [:error] [pid 1813]     process_report.delay(report.id)
[Wed Sep 16 04:51:33.480247 2020] [:error] [pid 1813]   File "/usr/lib/python2.7/site-packages/celery/app/task.py", line 412, in delay
[Wed Sep 16 04:51:33.480250 2020] [:error] [pid 1813]     return self.apply_async(args, kwargs)
[Wed Sep 16 04:51:33.480253 2020] [:error] [pid 1813]   File "/usr/lib/python2.7/site-packages/celery/app/task.py", line 535, in apply_async
[Wed Sep 16 04:51:33.480256 2020] [:error] [pid 1813]     **options
[Wed Sep 16 04:51:33.480258 2020] [:error] [pid 1813]   File "/usr/lib/python2.7/site-packages/celery/app/base.py", line 737, in send_task
[Wed Sep 16 04:51:33.480261 2020] [:error] [pid 1813]     amqp.send_task_message(P, name, message, **options)
[Wed Sep 16 04:51:33.480264 2020] [:error] [pid 1813]   File "/usr/lib/python2.7/site-packages/celery/app/amqp.py", line 558, in send_task_message
[Wed Sep 16 04:51:33.480267 2020] [:error] [pid 1813]     **properties
[Wed Sep 16 04:51:33.480269 2020] [:error] [pid 1813]   File "/usr/lib/python2.7/site-packages/kombu/messaging.py", line 181, in publish
[Wed Sep 16 04:51:33.480272 2020] [:error] [pid 1813]     exchange_name, declare,
[Wed Sep 16 04:51:33.480275 2020] [:error] [pid 1813]   File "/usr/lib/python2.7/site-packages/kombu/connection.py", line 527, in _ensured
[Wed Sep 16 04:51:33.480278 2020] [:error] [pid 1813]     errback and errback(exc, 0)
[Wed Sep 16 04:51:33.480280 2020] [:error] [pid 1813]   File "/usr/lib64/python2.7/contextlib.py", line 35, in __exit__
[Wed Sep 16 04:51:33.480283 2020] [:error] [pid 1813]     self.gen.throw(type, value, traceback)
[Wed Sep 16 04:51:33.480286 2020] [:error] [pid 1813]   File "/usr/lib/python2.7/site-packages/kombu/connection.py", line 419, in _reraise_as_library_errors
[Wed Sep 16 04:51:33.480288 2020] [:error] [pid 1813]     sys.exc_info()[2])
[Wed Sep 16 04:51:33.480291 2020] [:error] [pid 1813]   File "/usr/lib/python2.7/site-packages/kombu/connection.py", line 414, in _reraise_as_library_errors
[Wed Sep 16 04:51:33.480294 2020] [:error] [pid 1813]     yield
[Wed Sep 16 04:51:33.480305 2020] [:error] [pid 1813]   File "/usr/lib/python2.7/site-packages/kombu/connection.py", line 515, in _ensured
[Wed Sep 16 04:51:33.480308 2020] [:error] [pid 1813]     reraise_as_library_errors=False,
[Wed Sep 16 04:51:33.480311 2020] [:error] [pid 1813]   File "/usr/lib/python2.7/site-packages/kombu/connection.py", line 405, in ensure_connection
[Wed Sep 16 04:51:33.480314 2020] [:error] [pid 1813]     callback)
[Wed Sep 16 04:51:33.480316 2020] [:error] [pid 1813]   File "/usr/lib/python2.7/site-packages/kombu/utils/functional.py", line 333, in retry_over_time
[Wed Sep 16 04:51:33.480324 2020] [:error] [pid 1813]     return fun(*args, **kwargs)
[Wed Sep 16 04:51:33.480327 2020] [:error] [pid 1813]   File "/usr/lib/python2.7/site-packages/kombu/connection.py", line 261, in connect
[Wed Sep 16 04:51:33.480329 2020] [:error] [pid 1813]     return self.connection
[Wed Sep 16 04:51:33.480332 2020] [:error] [pid 1813]   File "/usr/lib/python2.7/site-packages/kombu/connection.py", line 802, in connection
[Wed Sep 16 04:51:33.480334 2020] [:error] [pid 1813]     self._connection = self._establish_connection()
[Wed Sep 16 04:51:33.480337 2020] [:error] [pid 1813]   File "/usr/lib/python2.7/site-packages/kombu/connection.py", line 757, in _establish_connection
[Wed Sep 16 04:51:33.480339 2020] [:error] [pid 1813]     conn = self.transport.establish_connection()
[Wed Sep 16 04:51:33.480342 2020] [:error] [pid 1813]   File "/usr/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 130, in establish_connection
[Wed Sep 16 04:51:33.480345 2020] [:error] [pid 1813]     conn.connect()
[Wed Sep 16 04:51:33.480347 2020] [:error] [pid 1813]   File "/usr/lib/python2.7/site-packages/amqp/connection.py", line 288, in connect
[Wed Sep 16 04:51:33.480350 2020] [:error] [pid 1813]     self.drain_events(timeout=self.connect_timeout)
[Wed Sep 16 04:51:33.480352 2020] [:error] [pid 1813]   File "/usr/lib/python2.7/site-packages/amqp/connection.py", line 471, in drain_events
[Wed Sep 16 04:51:33.480355 2020] [:error] [pid 1813]     while not self.blocking_read(timeout):
[Wed Sep 16 04:51:33.480357 2020] [:error] [pid 1813]   File "/usr/lib/python2.7/site-packages/amqp/connection.py", line 476, in blocking_read
[Wed Sep 16 04:51:33.480360 2020] [:error] [pid 1813]     frame = self.transport.read_frame()
[Wed Sep 16 04:51:33.480362 2020] [:error] [pid 1813]   File "/usr/lib/python2.7/site-packages/amqp/transport.py", line 236, in read_frame
[Wed Sep 16 04:51:33.480365 2020] [:error] [pid 1813]     payload = read(size)
[Wed Sep 16 04:51:33.480368 2020] [:error] [pid 1813]   File "/usr/lib/python2.7/site-packages/amqp/transport.py", line 409, in _read
[Wed Sep 16 04:51:33.480371 2020] [:error] [pid 1813]     raise IOError('Socket closed')
[Wed Sep 16 04:51:33.480373 2020] [:error] [pid 1813] OperationalError: Socket closed
`

**Comment by jaydeepjc** [comment]
As per Error `/patchman/reports/upload/` directory was not existed so Created it and changed `/etc/httpd/conf.d/patchman.conf file as below

`
Define patchman_pythonpath /usr/lib/python2.7/site-packages
#Define patchman_pythonpath /srv/patchman/
WSGIScriptAlias /patchman ${patchman_pythonpath}/patchman/wsgi.py
WSGIPythonPath ${patchman_pythonpath}

<Directory ${patchman_pythonpath}>
    <Files wsgi.py>
        Require all granted
    </Files>
    AllowOverride All
</Directory>

Alias /patchman/static "/var/lib/patchman/static"
<Location /patchman/static>
    SetHandler None
</Location>

<Directory /var/lib/patchman/static>
    Require all granted
</Directory>

<Directory /patchman/reports/upload>
    Require all granted
</Directory>

<Location /patchman/reports/upload>
    # Add the IP addresses of your client networks/hosts here
    # to allow uploading of reports
    Require ip 127.0.0.0/255.0.0.0
    Require all granted
    Require ip ::1/128
</Location>
`

**Comment by furlongm** [comment]
For one thing, you might try to remove the following lines from the upload location direction.

Require ip 127.0.0.0/255.0.0.0
Require ip ::1/128

**Comment by jaydeepjc** [comment]
I tried that too

```
Define patchman_pythonpath /usr/lib/python2.7/site-packages
WSGIScriptAlias /patchman ${patchman_pythonpath}/patchman/wsgi.py
WSGIPythonPath ${patchman_pythonpath}

<Directory ${patchman_pythonpath}>
    <Files wsgi.py>
        Require all granted
    </Files>
    AllowOverride All
</Directory>

Alias /patchman/static "/var/lib/patchman/static"
<Location /patchman/static>
    SetHandler None
</Location>

<Directory /var/lib/patchman/static>
    Require all granted
</Directory>

<Location /patchman/reports/upload>
    # Add the IP addresses of your client networks/hosts here
    # to allow uploading of reports
     Require ip 172.31.120.208/255.255.255.0
    Require all granted
    
</Location>
```

Still getting Same error
```
<h1>500 - Server Error</h1>
<p>There has been an error. It has been reported to the site administrators and should be fixed shortly.<p>
```

**Comment by furlongm** [comment]
Can you try setting DEBUG=True in /etc/patchman/local_settings.py ? Also check the web server error logs for the reason for the 500.

**Comment by jaydeepjc** [comment]
I did, It gives same error as mentioned in Above

**Comment by furlongm** [comment]
Looks like a celery/rabbitmq error.

Is celery running per the docs? Is rabbitmq running?

If you set `USE_ASYNC_PROCESSING = False` in patchman local_settings, it'll probably fix it too, but then you lose automatic report processing and need to set up a cronjob.

**Comment by jaydeepjc** [comment]
Noe not getting any error But still not seeing any entries in updates

![image](https://user-images.githubusercontent.com/6690868/94023470-dca5c680-fdd3-11ea-91f7-82a03ddf8503.png)

![image](https://user-images.githubusercontent.com/6690868/94023548-f7783b00-fdd3-11ea-89be-ae493d2f34a7.png)

**Comment by furlongm** [comment]
To get updates, you would need to set up a cronjob per the docs or fix your rabbitmq server and get celery working again.

**Comment by jaydeepjc** [comment]
I already set cronjob

```
[root@patchman ~]#  crontab -l
* * * * * /usr/bin/patchman -p
```

**Comment by jaydeepjc** [comment]
Solved above, also installed rabbitmq server and get celery working.
Now able to see updates in dashboard.
![image](https://user-images.githubusercontent.com/6690868/94104611-0d7a1000-fe55-11ea-9983-90b498c274a2.png)
what is first column entry for as I can see it empty? 

So my query is, if rabbitmq and celery is working on server, Then on client side do I need to do something apart from installing patchman-client?
Or it will automatically fetch all details

**Comment by furlongm** [comment]
The first column is security updates, the second column is bugfix updates.

The client only needs patchman-client installed in all cases.

**Comment by jaydeepjc** [comment]
Got it, Thanks a Lot Marcus.

At present I am running cronjob on server and client both

On Server `patchman -a` running in Cron
and On Client `patchman -r` running in Cron

**Comment by furlongm** [comment]
On the client, you should not run `patchman`, only `patchman-client`. You don't need the `patchman` package installed on the client.

**Comment by jaydeepjc** [comment]
Sorry it was typo I am running in client  patch man-client -r

**Comment by furlongm** [comment]
Just checking - it looks like everything is working now? Or is there still an issue?

**Comment by jaydeepjc** [comment]
Hi Marcus,

Everything is working fine.

Thanks a lot for your timely help. 👍
