### ISSUE TITLE
InvalidTemplateLibrary at /login/  (Build from source)

### ISSUE THREAD

**Issue by tarunz001** [furlongm/patchman#254]
Hi All,
I am trying to setup patchman tool in ubuntu 18.01 (bionic) & I have been trying to build patchman from source.
I followed similar steps as asked @ https://github.com/furlongm/patchman/blob/master/INSTALL.md#ubuntu-1804-bionic-1
Further, The installation is completed without any errors but when i hit url as : 
 http://<ip_address>/patchman

I am getting below error:

Request Method: | GET
-- | --
http://10.177.209.84/patchman/login/?next=/patchman/dashboard/
1.10
InvalidTemplateLibrary
Invalid template library specified. ImportError raised when trying to load 'bootstrap3.templatetags.bootstrap3': No module named parse
/usr/local/lib/python2.7/dist-packages/django/template/backends/django.py in get_package_libraries, line 130
/usr/bin/python
2.7.17
['/srv/patchman',  '/usr/lib/python2.7',  '/usr/lib/python2.7/plat-x86_64-linux-gnu',  '/usr/lib/python2.7/lib-tk',  '/usr/lib/python2.7/lib-old',  '/usr/lib/python2.7/lib-dynload',  '/usr/local/lib/python2.7/dist-packages',  '/usr/lib/python2.7/dist-packages']

Please pardon being novice to django & python, I am sure been making some silly mistake.

Below is output for the command : "pip freeze"
asn1crypto==0.24.0
beautifulsoup4==4.6.0
certifi==2018.1.18
chardet==3.0.4
colorama==0.3.7
cracklib==2.9.2
cryptography==2.1.4
defusedxml==0.5.0
Django==1.10
django-bootstrap3==12.1.0
django-extensions==1.8.1
django-filter==1.1.0
django-guardian==1.4.9
django-humanize==0.1.2
django-tagging==0.4.5
djangorestframework==3.7.7
dnspython==1.15.0
enum34==1.1.6
gyp==0.1
html5lib==0.999999999
humanize==0.5.1
idna==2.6
ipaddress==1.0.17
ipcalc==1.99.0
keyring==10.6.0
keyrings.alt==3.0
lxml==4.2.1
Markdown==2.6.9
progressbar==2.3
psycopg2==2.7.4
pycrypto==2.6.1
Pygments==2.2.0
pygobject==3.26.1
pygooglechart==0.4.0
pyOpenSSL==17.5.0
python-apt==1.6.5+ubuntu0.3
python-debian==0.1.32
python-magic==0.4.16
pytz==2018.3
pyxdg==0.25
PyYAML==3.12
requests==2.18.4
rpm==4.14.1
SecretStorage==2.3.1
six==1.11.0
sqlparse==0.2.4
urllib3==1.22
webencodings==0.5

Best Regards,
Tarun Kumar

**Comment by furlongm** [comment]
Try `pip install django-bootstrap3==11.1.0`

**Comment by tarunz001** [comment]
Thanks a ton, @furlongm, 

You saved my further struggle, might have taken quite a good time further being a novice.

1 more query @furlongm  sir, Below command isn't working that's the reason I had to for source build, giving error:
`apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 0412F522`

Error:
`gpg: keyserver receive failed: No name
`

Thanks a lot for help once again @furlongm !!

**Comment by tarunz001** [comment]
closing it as issue is fixed. wrong bootstrap3 version was being used.
