### ISSUE TITLE
SLES: Zypper repos configured but not being pushed to patchman server

### ISSUE THREAD

**Issue by tarunz001** [furlongm/patchman#258]
https://github.com/furlongm/patchman/blob/804824bd5c4e149cc560ee3144783c5f1fd0cb60/client/patchman-client#L334

Hi @furlongm 
Thanks for all your efforts and help!!

Further, Now i have this patchman-client interacting with patchman server but issue is zypper repo information is not being pushed to server as part of report being sent.
Although , the zypper repo are correctly configured. 

```
# zypper lr
Repository priorities are without effect. All enabled repositories share the same priority.

#  | Alias                                                                             | Name                                                                                   | Enabled | GPG Check | Refresh
---+-----------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+---------+-----------+--------
 1 | geos-current-SLE-15-SP1-Desktop-NVIDIA-Driver for x86_64 WE                       | xxxx:geos-current-SLE-15-SP1-Desktop-NVIDIA-Driver for x86_64 WE                       | Yes     | ( p) Yes  | Yes
 2 | geos-current-SLE-Manager-Tools15-Debuginfo-Pool for x86_64 SP1                    | xxxx:geos-current-SLE-Manager-Tools15-Debuginfo-Pool for x86_64 SP1                    | Yes     | ( p) Yes  | Yes
```

So, as you could see above two are enabled as well, arent these valid.

Thanks in advance!!

**Comment by furlongm** [comment]
Can you paste the output of `zypper --no-refresh lr -E -u --details`?

**Comment by tarunz001** [comment]
Thanks for replying @furlongm, below is output:

# zypper --no-refresh lr -E -u --details
#  | Alias                                                          | Name                                                                | Enabled | GPG Check | Refresh | Priority | Type   | URI                                                                                                                 | Service
---+----------------------------------------------------------------+---------------------------------------------------------------------+---------+-----------+---------+----------+--------+---------------------------------------------------------------------------------------------------------------------+--------
 1 | geos-current-SLE-15-SP1-Desktop-NVIDIA-Driver for x86_64 WE    | xxxx:geos-current-SLE-15-SP1-Desktop-NVIDIA-Driver for x86_64 WE    | Yes     | ( p) Yes  | Yes     |   99     | rpm-md | http://fakedns.com/ks/dist/child/geos-current-sle-15-sp1-desktop-nvidia-driver-we/geos-current           |
 2 | geos-current-SLE-Manager-Tools15-Debuginfo-Pool for x86_64 SP1 | XXXX:geos-current-SLE-Manager-Tools15-Debuginfo-Pool for x86_64 SP1 | Yes     | ( p) Yes  | Yes     |   99     | rpm-md | http://fakedns.com/ks/dist/child/geos-current-sle-manager-tools15-debuginfo-pool-x86_64-sp1/geos-current |

**Comment by furlongm** [comment]
Can you try this version of the client?

https://github.com/furlongm/patchman/blob/fix-zypper-lr/client/patchman-client

**Comment by furlongm** [comment]
Specifically, the change in 1d22ef0

**Comment by tarunz001** [comment]
@furlongm, That worked a charm 🚀 

I could see the two enabled zypper repo been pushed as well this time.

Thanks for the changes made sir 👍 :)

**Comment by furlongm** [comment]
Can you try the updated version now? I will merge it if it works.

**Comment by tarunz001** [comment]
sorry @furlongm for delayed response as i checked it now. 

checked fix-zypper-lr . its working super!!

Thanks & Regards,
Tarun Kumar
