### ISSUE TITLE
gets error 500 on debian jessie after install

### ISSUE THREAD

**Issue by ouzo12** [furlongm/patchman#27]
Seems like it redirects and then gets error 500.

Debug info

Request Method: 	GET
Request URL: 	http://XXX.XXX.XX.XXX/patchman/login/?next=/patchman/dashboard/
Django Version: 	1.7.11
Exception Type: 	AttributeError
Exception Value:        'dict' object has no attribute 'render_context'
Exception Location: 	/usr/lib/python2.7/dist-packages/django/template/base.py in render, line 146
Python Executable: 	/usr/bin/python
Python Version: 	2.7.9
Python Path: 	['/opt/patchman',
 '/opt/patchman/patchman',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/pymodules/python2.7']

**Comment by furlongm** [comment]
Django 1.8 is the minimum required version. Please see the following link for full instructions:

https://github.com/furlongm/patchman/blob/master/INSTALL#L29

The jessie-backports repo should have Django 1.8

**Comment by furlongm** [comment]
Actually, you may need to create a file like `/etc/apt/preferences.d/jessie-backports` with the following content:

```shell
Package: *
Pin: release n=jessie-backports
Pin-Priority: 1000
```

This will give the jessie-backports packages a higher priority and they will get installed.

**Comment by ouzo12** [comment]
Ah so simple... Thanks :) But you might add the preferences.d into the install file :)

**Comment by furlongm** [comment]
Instructions added to INSTALL
