### ISSUE TITLE
patchman-client YUM multi-language support

### ISSUE THREAD

**Issue by IPv777** [furlongm/patchman#272]
Hello 👍 

I found this function in patchman-client : 
![image](https://user-images.githubusercontent.com/19636346/103307810-5243b300-4a11-11eb-8808-0a5bc7b95fb2.png)

So (in my case) on a french CentOS where yum outputs french text, this code don't works as expected and 0 Repos appears instead of 12
![image](https://user-images.githubusercontent.com/19636346/103308042-cc743780-4a11-11eb-91fa-b7df89683fc0.png)

![image](https://user-images.githubusercontent.com/19636346/103307934-86b76f00-4a11-11eb-8c5f-30fe4d34601c.png)

Could you improve this code to support other language than english ?

Thanks ! :)

**Comment by IPv777** [comment]
Ok, I found a monkey-workaround : launch client with `LANGUAGE=en patchman-client`

**Comment by furlongm** [comment]
The should be fixed with b1a5681d56343508e552f4ef95b61517013e5d1c
