### ISSUE TITLE
patchman-client repo debian buster

### ISSUE THREAD

**Issue by ouzo12** [furlongm/patchman#273]
Im starting getting this error. Both on newly created servers and old servers... Only tried it on Debian Buster.

Ign:4 https://repo.openbytes.ie/debian buster InRelease                 
Err:5 https://repo.openbytes.ie/debian buster Release
  Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 37.247.48.91 443]

**Comment by IPv777** [comment]
Yes, me too... Seems the GPG key has changed...

Previously https://keyserver.ubuntu.com/pks/lookup?search=0x0412F522&fingerprint=on&op=index
but now https://keyserver.ubuntu.com/pks/lookup?search=0xFCAAD24A&fingerprint=on&op=index

@furlongm must we trust this key FCAAD24A ?

**Comment by Lejooohn** [comment]
same for me : 

openssl s_client -CAfile /etc/ssl/certs/ca-certificates.crt -showcerts -connect repo.openbytes.ie:443 < /dev/null
CONNECTED(00000003)
depth=0 CN = openbytes.ie
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 CN = openbytes.ie
verify error:num=21:unable to verify the first certificate
verify return:1

**Comment by IPv777** [comment]
Ok, I found a monkey-workaround (don't do this) : adding the intermediate certificate (Let's Encrypt R3) to the CA store.
```
curl -o /usr/local/share/ca-certificates/LE_R3.crt https://letsencrypt.org/certs/lets-encrypt-r3.pem 
update-ca-certificates
```

But I think the problme comes from the webserver of repo.openbytes.ie, maybe you need to use fullchain.pem @furlongm ?

**Comment by furlongm** [comment]
Looks like it's related to 

   https://letsencrypt.org/2020/11/06/own-two-feet.html

and/or

   https://community.letsencrypt.org/t/beginning-issuance-from-r3/

The certs are auto-generated each month so I'll need to update the software that does that. In the meantime I have restored the certs from Dec 2020 and it seems to work fine now.

**Comment by Lejooohn** [comment]
> 
> 
> Looks like it's related to
> 
> https://letsencrypt.org/2020/11/06/own-two-feet.html
> 
> and/or
> 
> https://community.letsencrypt.org/t/beginning-issuance-from-r3/
> 
> The certs are auto-generated each month so I'll need to update the software that does that. In the meantime I have restored the certs from Dec 2020 and it seems to work fine now.

Thank you @furlongm i confirm all is working fine now 👍

**Comment by furlongm** [comment]
This is fixed now.
