### ISSUE TITLE
Debian Only

### ISSUE THREAD

**Issue by jrsmile** [furlongm/patchman#283]
Hi,

first of all thank you for this simple to use very effective patch monitoring solution.
Especially for Debian there was no good solution until now.

We in our Company have a pure Debian Environment and i just wanted to know what steps have to be done to remove errata from centos and speed up the patchman -a process.

Furthermore is it possible to disable rdns check for all hosts?

**Comment by jrsmile** [comment]
another question, would it be possible to provide the patchman-client package for debian 9 and 8 ?

**Comment by furlongm** [comment]
The same deb should work on older debian releases?

The 2.0 release will disable rdns checks, and will also remove downloading errata by default. Check out the `develop` branch for the updates there.

**Comment by jrsmile** [comment]
thank you, i just realized there are multiple dist folders in the repo, time to install some deps :-) 
thanks again for this solution.
