### ISSUE TITLE
Security patches counter for CentOS does not work

### ISSUE THREAD

**Issue by rodkevchen** [furlongm/patchman#290]
Hi Marcus,

first thank you for this great project. I searching for a while for such tool.

I setup the toll and everything works fine so far. The only issue we have is that the counter for the security patches does not work for our CentOS machines. We already run `patchman -a` to get everything on the latest state. But it does not work.

We also run `patchman -e` manually and patchman collect all the data so far but still no patches are counted which are security relevant.

I dont think that this is a bug maybe a misconfiguration but I dont find anything so far which is related to this problem.

It would be greate if you maybe have some hints for us to solve the problem.

Best,

**Comment by furlongm** [comment]
Which version of patchman are you using?

If you go into the django admin interface, how many errata are there?

**Comment by rodkevchen** [comment]
Thanks for your reply currently we are using the latest version 1.2.24.

Django admin interface says that currently there are 6274 Errata entrys.

**Comment by furlongm** [comment]
Hmm, I've got 9936 Errata entries. Maybe delete them and run `patchman -e` again? There was a bug where some got skipped before.

**Comment by furlongm** [comment]
Actually - don't bother, I think I know why - some of the older ones got deleted upstream due to Centos 5 being removed.

**Comment by furlongm** [comment]
What version of CentOS are you using?

**Comment by rodkevchen** [comment]
We currently added 4 different hosts with dofferent CentOS Versions. I added a screenshot.
![image](https://user-images.githubusercontent.com/46161675/109755521-76c13480-7be6-11eb-97fa-c1c145616e37.png)

**Comment by furlongm** [comment]
This should be fixed with 585f14dfb852a8f4793d6787094c777cdeb360ee and 7e13fccbb955cfefd1f24a958cb06596e022df9b

You will probably need to delete all the existing errata via the django admin interface, then run `patchman -d` to clean up the bad packages, and then run `patchman -e` to repopulate the errata.
