### ISSUE TITLE
SLES 12 patchman-client -u Parameter doesnt work

### ISSUE THREAD

**Issue by meikelF** [furlongm/patchman#292]
Hi,
I am testing patchman and have a problem with a SLES12 client. The repository is protected, the updates should be found locally (like REHL). When I use the parameter -u I get the following error message:

vxxx:~ # patchman-client -v -u -h vxxx.xxx.local
/usr/sbin/patchman-client: illegal option -- u
/usr/sbin/patchman-client [-v] [-d] [-n] [-u] [-r] [-s SERVER] [-c FILE] [-t TAGS] [-h HOSTNAME]
-v: verbose output (default is silent)
-d: debug output
-n: no repo check (required when used as an apt or yum plugin)
-u: find updates locally (e.g. for RHEL)
-r: request a report from the server (default is no report)
-s SERVER: web server address, e.g. https://patchman.example.com
-c FILE: config file location (default is /etc/patchman/patchman-client.conf)
-t TAGS: comma-separated list of tags, e.g. -t www,dev
-h HOSTNAME: specify the hostname of the local host

Command line options override config file options.

Kind Regards, Michael

**Comment by furlongm** [comment]
Thanks for the report.

169c93388c5915ba4e012e80a66bbc60a71f38d1 and 3f82765977caa0c415b515e97b974ef010c0840e should fix your issue. Tested with SLES 12 and 15.

**Comment by furlongm** [comment]
Just cut a new release that has a bunch of fixes related to updates. Can you try 1.2.26? (both client and server)

That should fix the issue.

**Comment by meikelF** [comment]
Tried 1.2.26 Server and Client. The option -u is now running on sles, but with error: 

/usr/sbin/patchman-client: line 482: 0: command not found

And with "zypper lp" I see some pending patches, but not in patchman. See Details below :

vxxxxx:~ # patchman-client -v -u -h vxxxxx.uta.local
Attempting to obtain lock: /var/lock/patchman/patchman.lock
Patchman configuration seems OK: /etc/patchman/patchman-client.conf
Patchman Server: http://vpatchman.uta.local/patchman
Hostname: vxxxxx.uta.local
Tags: Server
Report: 0
Finding installed rpms...
Finding zypper repos...
Finding updates locally for SLES12-SP5-Pool
Specified repository 'SLES12-SP5-Source-Pool' is disabled.
Finding updates locally for SLES12-SP5-Updates
Specified repository 'SLES12-SP5-Source-Pool' is disabled.
Finding updates locally for SLE-SDK12-SP5-Pool
Specified repository 'SLES12-SP5-Source-Pool' is disabled.
Finding updates locally for SLE-SDK12-SP5-Updates
Specified repository 'SLES12-SP5-Source-Pool' is disabled.
Finding updates locally for SLE-Module-Web-Scripting12-Pool
Specified repository 'SLES12-SP5-Source-Pool' is disabled.
Finding updates locally for SLE-Module-Web-Scripting12-Updates
Specified repository 'SLES12-SP5-Source-Pool' is disabled.
Sending data to http://vpatchman.uta.local/patchman with curl:
curl --insecure --connect-timeout 60 --max-time 300 -i -F host="vxxxxx.uta.local" -F tags="Server" -F kernel="4.12.14-122.60-default" -F arch="x86_64" -F protocol="1" -F os="SLES 12-SP5" -F report="0" -F packages=\</tmp/tmp.xnThLYRmRk -F repos=\</tmp/tmp.ZBEnrmylJ0 -F sec_updates=\</tmp/tmp.mP4UWVTjku -F bug_updates=\</tmp/tmp.K2Sk5a9pSz -F reboot="ServerCheck" http://vpatchman.uta.local/patchman/reports/upload/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 94472    0     0  100 94472      0  1317k --:--:-- --:--:-- --:--:-- 1317k
**/usr/sbin/patchman-client: line 482: 0: command not found**
HTTP/1.1 100 Continue

HTTP/1.1 204 No Content
Date: Fri, 05 Mar 2021 07:21:47 GMT
Server: Apache/2.4.29 (Ubuntu)
X-Frame-Options: SAMEORIGIN

Deleting /tmp/tmp.xnThLYRmRk
Deleting /tmp/tmp.ZBEnrmylJ0
Deleting /tmp/tmp.mP4UWVTjku
Deleting /tmp/tmp.K2Sk5a9pSz
vxxxxx:~ # zypper lp
Refreshing service 'SUSE_Linux_Enterprise_Server_12_SP5_x86_64'.
Refreshing service 'SUSE_Linux_Enterprise_Software_Development_Kit_12_SP5_x86_64'.
Refreshing service 'Web_and_Scripting_Module_12_x86_64'.
Loading repository data...
Reading installed packages...

Repository         | Name                            | Category | Severity  | Interactive | Status | Summary
-------------------+---------------------------------+----------+-----------+-------------+--------+----------------------------------------
SLES12-SP5-Updates | SUSE-SLE-SERVER-12-SP5-2021-663 | security | important | ---         | needed | Security update for open-iscsi
SLES12-SP5-Updates | SUSE-SLE-SERVER-12-SP5-2021-667 | security | important | ---         | needed | Security update for MozillaFirefox
SLES12-SP5-Updates | SUSE-SLE-SERVER-12-SP5-2021-675 | security | important | ---         | needed | Security update for python-cryptography
SLES12-SP5-Updates | SUSE-SLE-SERVER-12-SP5-2021-681 | security | important | ---         | needed | Security update for grub2
SLES12-SP5-Updates | SUSE-SLE-SERVER-12-SP5-2021-693 | security | important | ---         | needed | Security update for openldap2

Found 5 applicable patches:
**5 patches needed (5 security patches)**

vxxxxx:~ #


Process Report:
root@vpatchman:~# patchman -p -H xxxxx.uta.local
Processing Reports for Host xxxxx.uta.local
Reverse DNS matches
xxxxx.uta.local repos            100%|##############################################################################################################################################################################|Time: 0:00:00
xxxxx.uta.local packages         100%|##############################################################################################################################################################################|Time: 0:00:08
root@vpatchman:~#

root@vpatchman:~# patchman -u -H xxxxx.uta.local
Finding updates for Host xxxxx.uta.local
xxxxx.uta.local

root@vpatchman:~#

**Comment by furlongm** [comment]
Forgot to update the conf file. Please try with 1.2.27

**Comment by meikelF** [comment]
Hi Marcus,
I have still problems sles and -u parameter:

**Client:**

patchman-client -d -u -h client.patchman
Attempting to obtain lock: /var/lock/patchman/patchman.lock
Patchman configuration seems OK: /etc/patchman/patchman-client.conf
Patchman Server: http://patchman.server/patchman
Hostname: client.patchman
Tags: Server
Report: false
Hostname: client.patchman
Kernel:   4.12.14-122.60-default
Arch:     x86_64
OS:       SLES 12-SP5
Finding installed rpms...
'fribidi-32bit' '' '0.19.2' '12.66' 'x86_64' 'rpm'
'libbrasero-utils3-1' '' '3.12.1' '4.9' 'x86_64' 'rpm'
.
.
.
.
'yast2-sysconfig' '' '3.1.4' '3.5' 'noarch' 'rpm'
Finding zypper repos...
Finding updates locally for SLES12-SP5-Debuginfo-Pool
Finding updates locally for SLES12-SP5-Debuginfo-Updates
Finding updates locally for SLES12-SP5-Pool
Finding updates locally for SLES12-SP5-Source-Pool
Finding updates locally for SLES12-SP5-Updates
Finding updates locally for SLE-SDK12-SP5-Debuginfo-Pool
Finding updates locally for SLE-SDK12-SP5-Debuginfo-Updates
Finding updates locally for SLE-SDK12-SP5-Pool
Finding updates locally for SLE-SDK12-SP5-Source-Pool
Finding updates locally for SLE-SDK12-SP5-Updates
Finding updates locally for SLE-Module-Web-Scripting12-Pool
Finding updates locally for SLE-Module-Web-Scripting12-Updates
'rpm' 'SUSE_Linux_Enterprise_Server_12_SP5_x86_64:SLES12-SP5-Debuginfo-Pool x86_64' 'SLES12-SP5-Debuginfo-Pool' '99' 'https://updates.suse.com/SUSE/Products/SLE-SERVER/12-SP5/x86_64/product_debug'
'rpm' 'SUSE_Linux_Enterprise_Server_12_SP5_x86_64:SLES12-SP5-Debuginfo-Updates x86_64' 'SLES12-SP5-Debuginfo-Updates' '99' 'https://updates.suse.com/SUSE/Updates/SLE-SERVER/12-SP5/x86_64/update_debug'
'rpm' 'SUSE_Linux_Enterprise_Server_12_SP5_x86_64:SLES12-SP5-Pool x86_64' 'SLES12-SP5-Pool' '99' 'https://updates.suse.com/SUSE/Products/SLE-SERVER/12-SP5/x86_64/product'
'rpm' 'SUSE_Linux_Enterprise_Server_12_SP5_x86_64:SLES12-SP5-Source-Pool x86_64' 'SLES12-SP5-Source-Pool' '99' 'https://updates.suse.com/SUSE/Products/SLE-SERVER/12-SP5/x86_64/product_source'
'rpm' 'SUSE_Linux_Enterprise_Server_12_SP5_x86_64:SLES12-SP5-Updates x86_64' 'SLES12-SP5-Updates' '99' 'https://updates.suse.com/SUSE/Updates/SLE-SERVER/12-SP5/x86_64/update'
'rpm' 'SUSE_Linux_Enterprise_Software_Development_Kit_12_SP5_x86_64:SLE-SDK12-SP5-Debuginfo-Pool x86_64' 'SLE-SDK12-SP5-Debuginfo-Pool' '99' 'https://updates.suse.com/SUSE/Products/SLE-SDK/12-SP5/x86_64/product_debug'
'rpm' 'SUSE_Linux_Enterprise_Software_Development_Kit_12_SP5_x86_64:SLE-SDK12-SP5-Debuginfo-Updates x86_64' 'SLE-SDK12-SP5-Debuginfo-Updates' '99' 'https://updates.suse.com/SUSE/Updates/SLE-SDK/12-SP5/x86_64/update_debug'
'rpm' 'SUSE_Linux_Enterprise_Software_Development_Kit_12_SP5_x86_64:SLE-SDK12-SP5-Pool x86_64' 'SLE-SDK12-SP5-Pool' '99' 'https://updates.suse.com/SUSE/Products/SLE-SDK/12-SP5/x86_64/product'
'rpm' 'SUSE_Linux_Enterprise_Software_Development_Kit_12_SP5_x86_64:SLE-SDK12-SP5-Source-Pool x86_64' 'SLE-SDK12-SP5-Source-Pool' '99' 'https://updates.suse.com/SUSE/Products/SLE-SDK/12-SP5/x86_64/product_source'
'rpm' 'SUSE_Linux_Enterprise_Software_Development_Kit_12_SP5_x86_64:SLE-SDK12-SP5-Updates x86_64' 'SLE-SDK12-SP5-Updates' '99' 'https://updates.suse.com/SUSE/Updates/SLE-SDK/12-SP5/x86_64/update'
'rpm' 'Web_and_Scripting_Module_12_x86_64:SLE-Module-Web-Scripting12-Pool x86_64' 'SLE-Module-Web-Scripting12-Pool' '99' 'https://updates.suse.com/SUSE/Products/SLE-Module-Web-Scripting/12/x86_64/product'
'rpm' 'Web_and_Scripting_Module_12_x86_64:SLE-Module-Web-Scripting12-Updates x86_64' 'SLE-Module-Web-Scripting12-Updates' '99' 'https://updates.suse.com/SUSE/Updates/SLE-Module-Web-Scripting/12/x86_64/update'
Sending data to http://patchman.server/patchman with curl:
curl --insecure --connect-timeout 60 --max-time 300 -i -F host="client.patchman" -F tags="Server" -F kernel="4.12.14-122.60-default" -F arch="x86_64" -F protocol="1" -F os="SLES 12-SP5" -F report="false" -F packages=\</tmp/tmp.bXcKAjwA46 -F repos=\</tmp/tmp.bttxZOsIoL -F sec_updates=\</tmp/tmp.WwMAxJq0hg -F bug_updates=\</tmp/tmp.OulwOWDOkf -F reboot="ServerCheck" http://patchman.server/patchman/reports/upload/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 95643    0     0  100 95643      0  2668k --:--:-- --:--:-- --:--:-- 2668k
HTTP/1.1 100 Continue

HTTP/1.1 204 No Content
Date: Fri, 05 Mar 2021 17:02:15 GMT
Server: Apache/2.4.29 (Ubuntu)
X-Frame-Options: SAMEORIGIN

Debug: not deleting /tmp/tmp.bXcKAjwA46 (packages)
Debug: not deleting /tmp/tmp.bttxZOsIoL (repos)
Debug: not deleting /tmp/tmp.WwMAxJq0hg (security updates)
Debug: not deleting /tmp/tmp.OulwOWDOkf (updates)
clientgw:~ # ls -la /tmp/tmp.*
ls: cannot access '/tmp/tmp.*': No such file or directory
clientgw:~ #

client.patchman:~ # zypper lp
Refreshing service 'SUSE_Linux_Enterprise_Server_12_SP5_x86_64'.
Refreshing service 'SUSE_Linux_Enterprise_Software_Development_Kit_12_SP5_x86_64'.
Refreshing service 'Web_and_Scripting_Module_12_x86_64'.
Loading repository data...
Reading installed packages...

Repository         | Name                            | Category | Severity  | Interactive | Status | Summary
-------------------+---------------------------------+----------+-----------+-------------+--------+----------------------------------------
SLES12-SP5-Updates | SUSE-SLE-SERVER-12-SP5-2021-663 | security | important | ---         | needed | Security update for open-iscsi
SLES12-SP5-Updates | SUSE-SLE-SERVER-12-SP5-2021-667 | security | important | ---         | needed | Security update for MozillaFirefox
SLES12-SP5-Updates | SUSE-SLE-SERVER-12-SP5-2021-675 | security | important | ---         | needed | Security update for python-cryptography
SLES12-SP5-Updates | SUSE-SLE-SERVER-12-SP5-2021-681 | security | important | ---         | needed | Security update for grub2
SLES12-SP5-Updates | SUSE-SLE-SERVER-12-SP5-2021-693 | security | important | ---         | needed | Security update for openldap2

Found 5 applicable patches:
5 patches needed (5 security patches)

client.patchman:~ #




**Server:**
root@patchman.server:~# patchman -p -H client.patchman
Processing Reports for Host client.patchman
Reverse DNS matches
client.patchman repos             100%|##############################################################################################################################################################################|Time: 0:00:00
client.patchman packages          100%|##############################################################################################################################################################################|Time: 0:00:08
root@vpatchman:~# patchman -u -H client.patchman
Finding updates for Host client.patchman
client.patchman

root@patchman.server:~#

**Comment by furlongm** [comment]
Are any updates visible for the host in the UI _before_ you run `patchman -u -H client.patchman`? (but after submitting the report)

**Comment by furlongm** [comment]
3891fbc3eb92a461597f6813acd3c12f364f3866 should fix the `zypper lu` issue. The repo number was accidentally hardcoded.

Can you try with 1.2.29 and see if it works for you? (both client and server upgrade needed).

**Comment by meikelF** [comment]
Great job, it works.

Thank you
