### ISSUE TITLE
1.2.26-1 patchman -u broken on latest Ubuntu 18.04

### ISSUE THREAD

**Issue by ThomasReithGer** [furlongm/patchman#295]
Hello Marcus,
there seems to be a bug in 1.2.26 on Ubuntu 18.04.5. Version 1.2.25 worked.

---
patchman -u
Finding updates for all Hosts

xxx.edag.de
Traceback (most recent call last):
  File "/usr/bin/patchman", line 687, in <module>
    main()
  File "/usr/bin/patchman", line 681, in main
    showhelp = process_args(args)
  File "/usr/bin/patchman", line 651, in process_args
    host_updates(args.host)
  File "/usr/bin/patchman", line 332, in host_updates
    host.find_updates()
  File "/usr/lib/python2.7/dist-packages/hosts/models.py", line 207, in find_updates
    repo_packages)
  File "/usr/lib/python2.7/dist-packages/hosts/models.py", line 256, in find_host_repo_updates
    uid = self.process_update(package, highest_package)
  File "/usr/lib/python2.7/dist-packages/hosts/models.py", line 162, in process_update
    update = updates.get(oldpackage=package, newpackage=highest_package)
  File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 380, in get
    self.model._meta.object_name
packages.models.DoesNotExist: PackageUpdate matching query does not exist.
---

hope it helps and greetings from Germany

Thomas

**Comment by furlongm** [comment]
Can you try with 1.2.27?

**Comment by ThomasReithGer** [comment]
Hello Marcus,

good job, it works again :-)

Btw. The 1.2.27 rpm replaces /etc/patchman/patchman-client.conf with
the original one. Perhaps, it would be better to keep the existing file and
store the rpm file in /etc/patchman/patchman-client.conf.rpmsave

Running transaction
  Updating   : patchman-client-1.2.27-1.noarch                                                                                                      1/2
warning: /etc/patchman/patchman-client.conf saved as /etc/patchman/patchman-client.conf.rpmsave
  Cleanup    : patchman-client-1.2.26-1.noarch                                                                                                      2/2
  Verifying  : patchman-client-1.2.27-1.noarch                                                                                                      1/2
  Verifying  : patchman-client-1.2.26-1.noarch

Thanks and best wishes

Thomas


Mit freundlichen Grüßen  |  sincerely yours

i.A. Thomas Reith
Dipl. Inform.
Service Owner Managed Server
Team IT Operations

EDAG Engineering GmbH
Steinauer Str. 20
36100 Petersberg
Tel.: +49 661 6000 597
E-Mail: thomas.reith@edag.com<mailto:thomas.reith@edag.com>
www.edag.com<http://www.edag.com>

EDAG Engineering GmbH - A company of EDAG Group
YOUR GLOBAL MOBILITYENGINEERING EXPERTS



               



EDAG TECH INSIGHTS - insights for engineering experts#VehicleEngineering #ProductionSolutions #ElectricsElectronics #Software #DigitalisationStay up to date: insights.edag.com 




Hauptsitz / Headquarters: EDAG Engineering GmbH, Kreuzberger Ring 40, 65205 Wiesbaden, GermanyRegistergericht / Court of jurisdiction: Amtsgericht Wiesbaden, HRB 28257Geschäftsführung / Board of Managing Directors: Cosimo De Carlo - CEO, Harald Keller - COO, Holger Merz - CFOAufsichtsratsvorsitzender / Chairman of the Supervisory Board: Georg Denoke



Please consider the environment before printing this e-mail.



This e-mail may contain confidential and / or privileged information. If you are not the intended recipient (or have received this e-mail in error) please notify the sender immediately and destroy this e-mail. Any unauthorised copying, disclosure or distribution of the material in this e-mail is strictly forbidden.

**Comment by ThomasReithGer** [comment]
Sorry, for the email footer waste. I'll try to answer not via email next time ;-)

**Comment by ThomasReithGer** [comment]
see above

**Comment by ThomasReithGer** [comment]
Hi again,
I use foreman/ansible for bulk patching the systems. To prevent overwriting /etc/patchman/patchman-client.conf, the
following job commands worked for me on Ubuntu
...
DEBIAN_FRONTEND='noninteractive'; export DEBIAN_FRONTEND
apt-get update -y
apt-get -y -o Dpkg::Options::='--force-confdef' -o Dpkg::Options::='--force-confold' upgrade
apt-get -y -o Dpkg::Options::='--force-confdef' -o Dpkg::Options::='--force-confold' dist-upgrade
apt-get autoremove -y
apt-get clean
apt-get autoclean
...

There seems to be no such option for yum. Unfortunately, one have to find and replace /etc/patchman/patchman-client.conf
with /etc/patchman/patchman-client.conf.rpmsafe manually or via bulk job afterwards.

I hope it helps

Thomas

**Comment by ThomasReithGer** [comment]
know now, why you push out a new config. The parameter "report=0" has been changed to "report=false".
With "report=0" the error "/usr/sbin/patchman-client: line 482: 0: command not found" occurs. 
It seems, that I have to create a bulk replacement job, anyhow ;-)

Thomas

**Comment by furlongm** [comment]
I will add a backwards-compatible option to convert from integer to boolean to fix this issue,

**Comment by ThomasReithGer** [comment]
Hello Marcus,
no problem, the config files have been converted and everything works as expected, except https://github.com/furlongm/patchman/issues/294

**Comment by ThomasReithGer** [comment]
Good job, and thanks for your time
Greetings
Thomas

**Comment by furlongm** [comment]
Backwards-compatibility added in f9ea0aa939b3f1cb05b22d451ed8b45600dd09a7

**Comment by furlongm** [comment]
Changed to no longer overwrite existing client configs (for rpms) in 8309b2e579a6c5e3c30f4fc908cd00bc5423d5f4
