### ISSUE TITLE
CentOS 7, import locally generated update list import failled

### ISSUE THREAD

**Issue by meikelF** [furlongm/patchman#296]
Hi Marcus,

the command
patchman-client -v -u -h vdhcp-wlan-neu.xxx.xxx works successfully, but the import fails.

vdhcp-wlan-neu.xxx.xxx     100%|##############################################################################################################################################################################|Time: 0:00:00
vdhcp-wlan-neu.xxx.xxx  100%|##############################################################################################################################################################################|Time: 0:00:06
Traceback (most recent call last):
  File "/usr/bin/patchman", line 687, in <module>
    main()
  File "/usr/bin/patchman", line 681, in main
    showhelp = process_args(args)
  File "/usr/bin/patchman", line 641, in process_args
    process_reports(args.host, args.force)
  File "/usr/bin/patchman", line 473, in process_reports
    report.process(find_updates=False)
  File "/usr/lib/python2.7/dist-packages/reports/models.py", line 163, in process
    process_updates(report=self, host=host)
  File "/usr/lib/python2.7/dist-packages/reports/utils.py", line 107, in process_updates
    bug_updates = parse_updates(report.bug_updates, False)
  File "/usr/lib/python2.7/dist-packages/reports/utils.py", line 150, in parse_updates
    ulist[2])

Do you need further infos?

**Comment by furlongm** [comment]
Do you have the full stacktrace? It looks like there's a bit missing?

**Comment by meikelF** [comment]
Hi Marcus,
hope this is all:
Client

[root@vdhcp-wlan-neu ~]# patchman-client -v -u -h vdhcp-wlan-neu.xxx.xxx
Attempting to obtain lock: /var/lock/patchman/patchman.lock
Patchman configuration seems OK: /etc/patchman/patchman-client.conf
Patchman Server: http://patchman/patchman
Hostname: vdhcp-wlan-neu.xxx.xxx
Tags: Server
Report: 0
Finding installed rpms...
Finding yum repos...
Finding updates locally for base
Finding updates locally for epel
Finding updates locally for extras
Finding updates locally for isc-kea-1-7
Finding updates locally for isc-kea-1-7-noarch
Finding updates locally for isc-kea-1-7-source
Finding updates locally for isc-stork
Finding updates locally for isc-stork-noarch
Finding updates locally for isc-stork-source
Finding updates locally for pgdg-common
Finding updates locally for pgdg10
Finding updates locally for pgdg11
Finding updates locally for pgdg12
Finding updates locally for pgdg13
Finding updates locally for pgdg95
Finding updates locally for pgdg96
Finding updates locally for updates
Sending data to http://patchman/patchman with curl:
curl --insecure --connect-timeout 60 --max-time 300 -i -F host="vdhcp-wlan-neu.xxx.xxx" -F tags="Server" -F kernel="3.10.0-1160.6.1.el7.x86_64" -F arch="x86_64" -F protocol="1" -F os="CentOS Linux release 7.9.2009 (Core)" -F report="0" -F packages=\</tmp/tmp.2ihYz6JAm2 -F repos=\</tmp/tmp.nCATkNXeUT -F sec_updates=\</tmp/tmp.xlCGMFHTre -F bug_updates=\</tmp/tmp.iLSxgSrF6i -F reboot="ServerCheck" http://patchman/patchman/reports/upload/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 78947    0     0  100 78947      0  1609k --:--:-- --:--:-- --:--:-- 1640k
/usr/sbin/patchman-client: Zeile 482: 0: Kommando nicht gefunden.
HTTP/1.1 100 Continue

HTTP/1.1 204 No Content
Date: Tue, 09 Mar 2021 09:16:05 GMT
Server: Apache/2.4.29 (Ubuntu)
X-Frame-Options: SAMEORIGIN

Deleting /tmp/tmp.2ihYz6JAm2
Deleting /tmp/tmp.nCATkNXeUT
Deleting /tmp/tmp.xlCGMFHTre
Deleting /tmp/tmp.iLSxgSrF6i

Server

root@vpatchman:~# patchman -a
Cleaning Reports for all Hosts

vdhcp-wlan-neu.xxx.xxx
vsshgw.xxx.xxx
Processing Reports for all Hosts
Reverse DNS mismatch found: vdhcp-wlan-neu.xxx.xxx != srv-sles-12-sp4.xxx.xxx
vdhcp-wlan-neu.xxx.xxx repos     100%|##############################################################################################################################################################################|Time: 0:00:00
vdhcp-wlan-neu.xxx.xxx packages  100%|##############################################################################################################################################################################|Time: 0:00:06
Traceback (most recent call last):
  File "/usr/bin/patchman", line 687, in <module>
    main()
  File "/usr/bin/patchman", line 681, in main
    showhelp = process_args(args)
  File "/usr/bin/patchman", line 641, in process_args
    process_reports(args.host, args.force)
  File "/usr/bin/patchman", line 473, in process_reports
    report.process(find_updates=False)
  File "/usr/lib/python2.7/dist-packages/reports/models.py", line 163, in process
    process_updates(report=self, host=host)
  File "/usr/lib/python2.7/dist-packages/reports/utils.py", line 107, in process_updates
    bug_updates = parse_updates(report.bug_updates, False)
  File "/usr/lib/python2.7/dist-packages/reports/utils.py", line 150, in parse_updates
    ulist[2])
IndexError: list index out of range
root@vpatchman:~#
[CentOS_local.zip](https://github.com/furlongm/patchman/files/6107391/CentOS_local.zip)

**Comment by furlongm** [comment]
Can you try `LC_ALL=C patchman-client -v -u`?

**Comment by meikelF** [comment]
Hi Marcus,

great, it's working.
Can you insert it the script or shall I put it in the the crontab?

Kind Regards, Michael

**Comment by furlongm** [comment]
Added to the script in b1a5681d56343508e552f4ef95b61517013e5d1c
