### ISSUE TITLE
client denied by server

### ISSUE THREAD

**Issue by fone** [furlongm/patchman#304]
Can someone explain where on the patchman server I should edit for allowed clients?

In the apache error log I see this when running patchman-client from another machine.

[Wed Mar 24 21:02:48.108391 2021] [authz_core:error] [pid 25952:tid 140392346842880] [client 192.168.10.10:59812] AH01630: client denied by server configuration: /usr/lib/python2.7/dist-packages/patchman/wsgi.py

**Comment by furlongm** [comment]
In `/etc/apache2/conf-available/patchman.conf`:

https://github.com/furlongm/patchman/blob/master/etc/patchman/apache.conf.example#L22-L25
