### ISSUE TITLE
Please consider compressing reports

### ISSUE THREAD

**Issue by mihkelvain** [furlongm/patchman#32]
And another request.

Please consider compressing reports before they get sent to patchman host. Reason for that is to save network bandwidth while sending reports to host. In our environment we have some servers that are available over satellite connection and it would help to speed things up and, as mentioned, save a few bucks on network traffic.

I have not actually measured how much it would save though :)

**Comment by furlongm** [comment]
I am hoping to rewrite the client in python to use the REST API, so not sure I want to spend time on this. Happy to take a pull request if it's something you feel is worthwhile though.

**Comment by furlongm** [comment]
First attempt at this in ac15efe8ce831a96110f9056e93cb62ee3094665

Please let me know if that works for you.

**Comment by furlongm** [comment]
Closing pending review of other branch. If this is still required, please reopen issue.
