### ISSUE TITLE
Problems with Oracle EL 6 repo?

### ISSUE THREAD

**Issue by mihkelvain** [furlongm/patchman#33]
I've been playing with patchman for most of the weekend and noticed a problem with Oracle 6 repo. I don't know if it is patchman bug or OEL repo specialty.

```
PYTHONPATH=/opt/patchman /opt/patchman/sbin/patchman -r
....
Repository 47 : Oracle Linux 6Server Latest (x86_64) x86_64
Downloading repo info (1/2):       100%|###########################################|Time: 0:00:00
Found yum rpm repo - http://public-yum.oracle.com/repo/OracleLinux/OL6/latest/x86_64/repodata/repomd.xml
Downloading repo info (2/2):       100%|###########################################|Time: 0:00:00
Killed
```

And this causes patchman -a -q to fail. If I disable that repo and mirror in UI, then patchman -r succeeds.

**Comment by furlongm** [comment]
Looks like memory error? Are you running with DEBUG enabled?

**Comment by mihkelvain** [comment]
Hey.

Most likely this particular run and snipped was done with DEBUG enabled. But it did not work without DEBUG also.

I have actually ditched pathman, because it did not suit my needs, so I can't really provide any additional information. Sorry. I will close this issue.
