### ISSUE TITLE
[Suggestion] Distribute patchman-client as a binary or via pip

### ISSUE THREAD

**Issue by CluelessTechnologist** [furlongm/patchman#342]
Sometimes you want to modify a client as little as possible. 
Adding a APT repository or installing a deb package manually might not be an option.

Since patchman-client is quite minimal, I think it would be a good idea to have access to the binary in an easy way.
Similar to [docker-compose](https://docs.docker.com/compose/install/) or [nagios nrdp client](https://github.com/NagiosEnterprises/nrdp).

In the case of _nrdp_ it's just a simple bash or python script that invokes a POST request. From my limited knowledge it seems like patchman-client works similarly.

**Comment by furlongm** [comment]
It's just a bash script, and it's hosted on github, so you could always just curl https://raw.githubusercontent.com/furlongm/patchman/master/client/patchman-client

**Comment by furlongm** [comment]
Closing as there are many ways to distribute. Binary debs and rpms are provided and the shell script is freely available on github.
