### ISSUE TITLE
Data upload not working

### ISSUE THREAD

**Issue by cshabazian** [furlongm/patchman#354]
I've built two brand new CentOS 8 servers from minimal install, no third party packages or other configuration items other than adding a user account.  I then proceed to install patchman on the server with the following:
cat <<EOF >> /etc/yum.repos.d/openbytes.repo
[openbytes]
name=openbytes
baseurl=https://repo.openbytes.ie/patchman/el8
enabled=1
gpgcheck=0
EOF
dnf -y install epel-release
dnf makecache
dnf -y install patchman patchman-client
systemctl restart httpd
patchman-manage createsuperuser
firewall-cmd --add-service=http --permanent && firewall-cmd --reload
#_ NOTE: I can logon to the web interface at this point
patchman-manage makemigrations
patchman-manage migrate --run-syncdb
patchman-manage createsuperuser
patchman-manage collectstatic
patchman-client -v -s http://127.0.0.1/patchman/

So now I would expect this host to show up under hosts in the web interface, but there is nothing there.  The upload does seem to work properly:
#############################################################################
[root@localhost ~]# patchman-client -v -s http://127.0.0.1/patchman/
Attempting to obtain lock: /var/lock/patchman/patchman.lock
Patchman configuration seems OK:
Using configuration file: /etc/patchman/patchman-client.conf
Patchman Server: http://127.0.0.1/patchman/
Hostname: localhost
Tags: Server
report: false
local_updates: false
repo_check: true
verbose: true
debug: false
Kernel:   4.18.0-305.25.1.el8_4.x86_64
Arch:     x86_64
OS:       CentOS Linux release 8.4.2105
Finding installed rpms...
Finding yum repos...
Sending data to http://127.0.0.1/patchman/ with curl:
curl --insecure --connect-timeout 60 --max-time 300 -i -F host="localhost" -F tags="Server" -F kernel="4.18.0-305.25.1.el8_4.x86_64" -F arch="x86_64" -F protocol="1" -F os="CentOS Linux release 8.4.2105" -F report="false" -F packages=\</tmp/tmp.MDXFhV8RA8 -F repos=\</tmp/tmp.gajRxclbfC -F sec_updates=\</tmp/tmp.KvfRAIELW9 -F bug_updates=\</tmp/tmp.pcvsgGnQ5b -F reboot="ServerCheck" http://127.0.0.1/patchman/reports/upload/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 28598    0     0  100 28598      0  32460 --:--:-- --:--:-- --:--:-- 32460
HTTP/1.1 100 Continue

HTTP/1.1 204 No Content
Date: Wed, 10 Nov 2021 22:49:28 GMT
Server: Apache/2.4.37 (centos) mod_wsgi/4.6.4 Python/3.6
X-Frame-Options: SAMEORIGIN

Deleting /tmp/tmp.MDXFhV8RA8
Deleting /tmp/tmp.gajRxclbfC
Deleting /tmp/tmp.KvfRAIELW9
Deleting /tmp/tmp.pcvsgGnQ5b
#############################################################################
But nothing is there.

The "Client" system was also a new build with just the following:
cat <<EOF >> /etc/yum.repos.d/openbytes.repo
[openbytes]
name=openbytes
baseurl=https://repo.openbytes.ie/patchman/el8
enabled=1
gpgcheck=0
EOF
dnf -y install epel-release
dnf makecache
dnf -y install patchman-client
#_ add IP Address and hostname to /etc/hosts and test to ensure it resolves

And when I attempt to add this client to the server, I get a permissions issue:
#############################################################################
#_ patchman-client -v -s http://patch.example.com/patchman
Attempting to obtain lock: /var/lock/patchman/patchman.lock
Patchman configuration seems OK:
Using configuration file: /etc/patchman/patchman-client.conf
Patchman Server: http://patch.example.com/patchman
Hostname: localhost
Tags: Server
report: false
local_updates: false
repo_check: true
verbose: true
debug: false
Kernel:   4.18.0-305.25.1.el8_4.x86_64
Arch:     x86_64
OS:       CentOS Linux release 8.4.2105
Finding installed rpms...
Finding yum repos...
Sending data to http://patch.example.com/patchman with curl:
curl --insecure --connect-timeout 60 --max-time 300 -i -F host="localhost" -F tags="Server" -F kernel="4.18.0-305.25.1.el8_4.x86_64" -F arch="x86_64" -F protocol="1" -F os="CentOS Linux release 8.4.2105" -F report="false" -F packages=\</tmp/tmp.ckXZNrnIpn -F repos=\</tmp/tmp.IE0FdadwQW -F sec_updates=\</tmp/tmp.sCJNuKQ3S7 -F bug_updates=\</tmp/tmp.Bn7raSZmyA -F reboot="ServerCheck" http://patch.example.com/patchman/reports/upload/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0 23772  100   199    0     0  49750      0 --:--:-- --:--:-- --:--:-- 49750
HTTP/1.1 403 Forbidden
Date: Wed, 10 Nov 2021 22:52:22 GMT
Server: Apache/2.4.37 (centos) mod_wsgi/4.6.4 Python/3.6
Content-Length: 199
Connection: close
Content-Type: text/html; charset=iso-8859-1

`<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">`
`<html><head>`
`<title>403 Forbidden</title>`
`</head><body>`
`<h1>Forbidden</h1>`
`<p>You don't have permission to access this resource.</p>`
`</body></html>`
`Deleting /tmp/tmp.ckXZNrnIpn`
`Deleting /tmp/tmp.IE0FdadwQW`
`Deleting /tmp/tmp.sCJNuKQ3S7`
`Deleting /tmp/tmp.Bn7raSZmyA`
#############################################################################

I'm sure I'm missing something basic, but can't for the life of me figure it out.  FYI, I have tried setting selinux to permissive and turning off the firewall to see if they were causing the issues, but it didn't change anything.

**Comment by furlongm** [comment]
Maybe this should be clearer in the installation guide - but you need to set the allowed networks in the apache configuration file. See step 2 here: https://github.com/furlongm/patchman/blob/master/INSTALL.md#apache

The file is named differently on CentOS but the content to be changed is the same. i.e.

https://github.com/furlongm/patchman/blob/master/etc/patchman/apache.conf.example#L21-L26

**Comment by cshabazian** [comment]
Ok, adding the Require ip to /etc/httpd/conf.d/patchman.conf now allows the transfer of data, but there still isn't anything displayed in the web interface after it's been uploaded.

**Comment by cshabazian** [comment]
So the problem seems to be that the data is making it to the web server, but not getting into the sqlite3 database.  Doing a dump of the database: 
sqlite3 patchman.db "select * from hosts_host;"
returns no values.  I manually add a host via the web interface, and the same query then shows the system manually entered.

So, where do I start troubleshooting this?

cat /etc/patchman/local_settings.py
#############################################################################
# Django settings for patchman project.

DEBUG = False

ADMINS = (
    ('admin', 'admin@email.com'),
)

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': '/var/lib/patchman/db/patchman.db',
    }
}

# Local time zone for this installation. Choices can be found here:
# http://en.wikipedia.org/wiki/List_of_tz_zones_by_name
TIME_ZONE = 'America/New_York'

# Language code for this installation. All choices can be found here:
# http://www.i18nguy.com/unicode/language-identifiers.html
LANGUAGE_CODE = 'en-us'

# Create a unique string here, and don't share it with anybody.
SECRET_KEY = 'zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz'

# Add the IP addresses that your web server will be listening on,
# instead of '*'
ALLOWED_HOSTS = ['10.20.30.122', '10.20.31.119', '127.0.0.1', '*']

# Maximum number of mirrors to add or refresh per repo
MAX_MIRRORS = 5

# Number of days to wait before notifying users that a host has not reported
DAYS_WITHOUT_REPORT = 14

# Whether to run patchman under the gunicorn web server
RUN_GUNICORN = False

# Enable memcached
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION': '127.0.0.1:11211',
    }
}
#############################################################################
The db is created, but empty:
# ls -hal /var/lib/patchman/db/patchman.db
-rw-r--r--. 1 apache apache 580K Nov 11 13:54 /var/lib/patchman/db/patchman.db

**Comment by furlongm** [comment]
580K doesn't look empty?

Can you run `.tables` after running `sqlite patchman.db`?

Or
```
patchman-manage makemigrations
patchman-manage migrate --run-syncdb
```

**Comment by cshabazian** [comment]
The database gets created just fine, it just doesn't populate when I try to add a server using the patchman-client.  I run `patchman-client -v -s http://127.0.0.1/patchman/` and it gathers the data and uploads it, but then when I go to hosts in the web interface there is nothing there.  I even check the database directly with `sqlite3 /var/lib/patchman/db/patchman.db "select * from hosts_host;"` and I get a null result.  If I add a host manually via the web interface, the same query does return the manually added host.

**Comment by cshabazian** [comment]
Nevermind.  PEBCAK.  I do see it in reports, then I have to run the report.  I guess it is installed correctly, I just have to learn how to use it properly.

**Comment by furlongm** [comment]
If you don't have celery installed and configured, you will need to run ‘patchman -a‘ to process the reports

**Comment by furlongm** [comment]
Going to close this issue as it seems to be resolved. Feel free to reopen.
