### ISSUE TITLE
'RegexURLPattern' object has no attribute '_callback'

### ISSUE THREAD

**Issue by gasperzupancic** [furlongm/patchman#38]
Not sure what i did, just regular update and also installed latest version of django 1.11.8. Now on dashboard i get an error like this:

AttributeError at /dashboard/
'RegexURLPattern' object has no attribute '_callback'
Request Method:	GET
Request URL:	http://patchman.localhost/patchman/dashboard/
Django Version:	1.11.7
Exception Type:	AttributeError
Exception Value:	
'RegexURLPattern' object has no attribute '_callback'
Exception Location:	/usr/lib/python2.7/site-packages/rest_framework/urlpatterns.py in apply_suffix_patterns, line 27
Python Executable:	/usr/bin/python
Python Version:	2.7.5
Python Path:	
['/opt/patchman',
 '/opt/patchman/patchman',
 '/usr/lib64/python27.zip',
 '/usr/lib64/python2.7',
 '/usr/lib64/python2.7/plat-linux2',
 '/usr/lib64/python2.7/lib-tk',
 '/usr/lib64/python2.7/lib-old',
 '/usr/lib64/python2.7/lib-dynload',
 '/usr/lib64/python2.7/site-packages',
 '/usr/lib64/python2.7/site-packages/gtk-2.0',
 '/usr/lib/python2.7/site-packages']
Server time:	Mon, 27 Nov 2017 09:09:56 +0100

**Comment by furlongm** [comment]
Currently only tested with Django 1.8 as per requirements.txt. I'll look at what is required for upgrading and see if I can maintain backwards-compat.

**Comment by gasperzupancic** [comment]
Hey Marcus,

thanks for replying back. I've managed to fix it with "pip install -r
requirements.txt" :) So yes, it had to be an update. Anyways, thanks again,
patchman is really helpful at my place!

all good!
