### ISSUE TITLE
reset the user password in web

### ISSUE THREAD

**Issue by dezhnevo** [furlongm/patchman#381]
Hi, how can i reset the password for the WEB interface of patchman?
Have the root access to server itself, but no pass for the gui. 
Please advice, dont't want to reinstall it.
THX

**Comment by furlongm** [comment]
```patchman-manage changepassword *username*```

**Comment by dezhnevo** [comment]
Thank's, but how to manage the patchamn internal users?

**Comment by furlongm** [comment]
Use the Django admin link to edit the users.

**Comment by dezhnevo** [comment]
Sorry, can you please explain? What link

**Comment by dezhnevo** [comment]
How can i do it if i have no user/password :) But i fixed the problem. THX
