### ISSUE TITLE
Getting openbytes key from keyserver.ubuntu.com on bullseye

### ISSUE THREAD

**Issue by macrotex** [furlongm/patchman#383]
The installation instructions for installing patchman on Debian say to use the following command to download the signing key for the openbytes Debian package repository:
```
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 0412F522
```
However, if you execute the above command on a Debian bullseye machine you get these messages:
```
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
Executing: /tmp/apt-key-gpghome.uYNDPUxBov/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys 0412F522
gpg: keyserver receive failed: Server indicated a failure
```
Maybe it would be better to provide the public key for the openbytes repo directly as a file that could be dropped in /etc/apt/trusted.gpg.d

**Comment by furlongm** [comment]
Did it work if you tried it again?

Seems like a server error, worked for me:

```root@857781dade70:/# apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 0412F522
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
Executing: /tmp/apt-key-gpghome.JdzydiKPlq/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys 0412F522
gpg: key D30FB02B0412F522: public key "Marcus Furlong <furlongm@gmail.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1```

**Comment by macrotex** [comment]
It looks to be something related to DNS. I was able to get around the issue by messing around with my resolv.conf (see also [this StackExchange question](https://unix.stackexchange.com/questions/399027/gpg-keyserver-receive-failed-server-indicated-a-failure)). In short, it does not seem to be a patchman issue.
