### ISSUE TITLE
How do i setup on RedHat 7 machine

### ISSUE THREAD

**Issue by dhajoshi** [furlongm/patchman#40]
Hello, i am trying to setup patchman on RHEL7 machine, is there simple instruction available to setup server ?

Thanks,
DJ

**Comment by furlongm** [comment]
Most of the instructions from https://github.com/furlongm/patchman/blob/master/INSTALL should work (install epel and use yum instead of apt-get). Would be good to get a Centos/RHEL instructions up.

**Comment by furlongm** [comment]
Initial instructions added to INSTALL doc in bd57d3c3e807959ea4f0e7135bfff8647a8d5b01
