### ISSUE TITLE
ValueError: too many values to unpack

### ISSUE THREAD

**Issue by mhos** [furlongm/patchman#41]
Hello,

I am testing this out on my home lab and think this app is pretty awesome however, I am running into the following when running PYTHONPATH=/srv/patchman /srv/patchman/sbin/pa
tchman -a

Finding updates for all Hosts

banjo.example.com
dovecot-2.2.36-2.cp1162-x86_64 -> dovecot-1:2.2.10-8.el7-x86_64 (Bugfix)
filesystem-3.2-21.el7-x86_64 -> filesystem-3.2-25.el7-x86_64 (Bugfix)
mariadb-devel-10.2.16-1.el7.centos-x86_64 -> mariadb-devel-1:5.5.56-2.el7-x86_64 (Bugfi
x)
mariadb-server-10.2.16-1.el7.centos-x86_64 -> mariadb-server-1:5.5.56-2.el7-x86_64 (Bug
fix)
p0f-3.09b-1.cp1150-x86_64 -> p0f-3.09b-1.el7-x86_64 (Bugfix)
Traceback (most recent call last):
  File "/srv/patchman/sbin/patchman", line 593, in <module>
    main()
  File "/srv/patchman/sbin/patchman", line 588, in main
    showhelp = process_args(args)
  File "/srv/patchman/sbin/patchman", line 569, in process_args
    host_updates_alt(args.host)
  File "/srv/patchman/sbin/patchman", line 282, in host_updates_alt
    host.find_updates()
  File "/srv/patchman/patchman/hosts/models.py", line 197, in find_updates
    repo_packages)
  File "/srv/patchman/patchman/hosts/models.py", line 311, in find_kernel_updates
    self.check_if_reboot_required(host_highest)
  File "/srv/patchman/patchman/hosts/models.py", line 277, in check_if_reboot_required
    ver, rel = kernel.rsplit('-')
ValueError: too many values to unpack

I am not very good with python yet and don't know where to go from here.
Goet everything insalled and 3 servers added 2 Ubuntu 16.04 servers and one CentOS 7.5 server.
The above command appears to work as long as there aren't any packages updates.
Would really like to use this as it's exactly what I'm looking for.
Any assistance is appreciated.

Thanks

**Comment by furlongm** [comment]
Looks like a possible  bug parsing kernels. Do you have the reports from the clients?

**Comment by furlongm** [comment]
Closing this issue. Feel free to re-open if the issue continues.
