### ISSUE TITLE
Patchman not using memcached

### ISSUE THREAD

**Issue by kaiszy** [furlongm/patchman#433]
Hi,

i use patchman for ca. 80 Servers. I wonder because a nightly report run takes a very long time (about 6 hours). To speed up the process i add

```
# Enable memcached
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION': '127.0.0.1:11211',
    }
}

```

I reload apache2. But memcache will not be used:

```
[x@patchman userA]# memcached-tool 127.0.0.1:11211 display
  #  Item_Size  Max_age   Pages   Count   Full?  Evicted Evict_Time OOM
```

Have i to remove some cachefiles ?

**Comment by furlongm** [comment]
Looks like per-site caching needs to be enabled via middleware:

https://docs.djangoproject.com/en/2.2/topics/cache/#the-per-site-cache-1

**Comment by furlongm** [comment]
@kaiszy can you check #462 and see if that fixes your issue?
