### ISSUE TITLE
Patchman Server on CentOS 9

### ISSUE THREAD

**Issue by litebito** [furlongm/patchman#441]
Hi,

is Patchman server ready for CentOS 9?
can it be installed on CentOS 9 using the https://repo.openbytes.ie/patchman/el8/ repo ?

**Comment by furlongm** [comment]
It may work but I have not tested it yet. Let me know if you come across any issues

**Comment by furlongm** [comment]
#468 has a list of outstanding (upstream) rhel9/centos9 issues

**Comment by furlongm** [comment]
Version 3 released with support for EL9
