### ISSUE TITLE
KeyError: 'sha512' when adding a repo

### ISSUE THREAD

**Issue by rpelissi** [furlongm/patchman#454]
Hi,
Using latest patchman installed on debian 11 and adding a rocky linux 8
When I do patchman -a on the server it discovers that the node got an nvidia repo but does not seems to like it:

```
Found yum rpm repo - https://nvidia.github.io/libnvidia-container/stable/centos8/x86_64/repodata/repomd.xml
Downloading repo info (2/2):       100%|#############################################################################################|Time: 0:00:00
Traceback (most recent call last):
  File "/usr/bin/patchman", line 686, in <module>
    main()
  File "/usr/bin/patchman", line 680, in main
    showhelp = process_args(args)
  File "/usr/bin/patchman", line 646, in process_args
    refresh_repos(args.repo, args.force)
  File "/usr/bin/patchman", line 121, in refresh_repos
    repo.refresh(force)
  File "/usr/lib/python3/dist-packages/repos/models.py", line 86, in refresh
    refresh_rpm_repo(self)
  File "/usr/lib/python3/dist-packages/repos/utils.py", line 616, in refresh_rpm_repo
    refresh_yum_repo(mirror, data, mirror_url, ts)
  File "/usr/lib/python3/dist-packages/repos/utils.py", line 455, in refresh_yum_repo
    computed_checksum = get_checksum(data, Checksum[checksum_type])
  File "/usr/lib/python3.9/enum.py", line 408, in __getitem__
    return cls._member_map_[name]
KeyError: 'sha512'
```
The repo on the client has been added using:
`curl https://nvidia.github.io/nvidia-docker/centos8/nvidia-docker.repo > /etc/yum.repos.d/nvidia-docker.repo`

Anything I can do to fix this?
Thanks!

**Comment by rpelissi** [comment]
I found in the closed ticket a similar issue but not sure if it is related or what should I do with it. Any information is welcome :)

https://github.com/furlongm/patchman/issues/17

**Comment by furlongm** [comment]
Can you check if 3fe819042a4876ebf270bd59393bf34da13223db fixes it for you?

**Comment by rpelissi** [comment]
Hi!
Yes the code change is working perfectly fine to solve my issue :)
Thanks!

**Comment by rpelissi** [comment]
Do you want me to generate a patch/diff or a new release can fix this issue soon?
Anyway this issue can be closed. Thanks again and let me wish you and all the Patchman users a wonderful year 2023!

**Comment by furlongm** [comment]
There's a PR here: https://github.com/furlongm/patchman/pull/455

I'll merge after some testing, and there should be a release soon after.
