### ISSUE TITLE
Debian is failing to install v2.0.6

### ISSUE THREAD

**Issue by marcb4** [furlongm/patchman#458]
With the new update we can't install patchman anymore:

```
The following packages have unmet dependencies:
 patchman-client : Depends: which but it is not installable
                   Depends: mktemp but it is not installable
```

This is probably caused by https://github.com/furlongm/patchman/pull/403/commits/9741e7628ceb8c99a7b4014fe89666174889ae53

apt tries to download `which` and `mktemp`, but these are packages that aren't available in a repository or managed by apt. They are installed by default.

**Comment by hellcry37** [comment]
+1, same issue here
