### ISSUE TITLE
Server install on Ubuntu 22.04?

### ISSUE THREAD

**Issue by satxroadrunner** [furlongm/patchman#502]
Hello, I love the concept of patchman and was wondering (before I spend time on it) if this install will work with the latest Ubuntu LTS   22.04?  Also, will the PR security dependencies be updated soon?

**Comment by furlongm** [comment]
Tracking 2022/2023 distro support  in https://github.com/furlongm/patchman/pull/468

Security PRs will be merged once that PR goes though. Some can't go through yet as they break older installations.
