### ISSUE TITLE
Get current status for a host or list of hosts (API / Command line)

### ISSUE THREAD

**Issue by rpelissi** [furlongm/patchman#510]
Hi,
I really like this project and wanted to know if there is a way to get the current list/status of all registred client so I can create a report / email?
Maybe using command line or using API call if there is such infos available?
Let me know if I miss the functionality or point me to the right doc.
Thanks again for this great solution!

**Comment by furlongm** [comment]
Here's a gist that uses the API to create an Excel spreadsheet with clients and updates available: https://gist.github.com/furlongm/a194697b7aa171411b7fffe2a64b06cc

**Comment by rpelissi** [comment]
That just perfect thanks! I will play with this and I am sure if will solve my reporting issue :)
Thanks!

**Comment by furlongm** [comment]
You're welcome!
