### ISSUE TITLE
Use patchman with https

### ISSUE THREAD

**Issue by rpelissi** [furlongm/patchman#511]
Hi!
Is there some docs to follow in order to use patchman (client > server and server webgui access) with https?
I can try to make it work on my side, just wanted to know is something already exist :)

The main reason is that port 80 is not allowed in my environement so having 443 used for client to server communication and webgui access as well will be very convienent.
Thanks!

**Comment by HilkopterBob** [comment]
Hey, [Apache SSL-Docs](https://httpd.apache.org/docs/2.4/ssl/ssl_howto.html) or [NGINX Reverse Proxy](https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/) would be viable solutions

**Comment by rpelissi** [comment]
Yep I got it working with apache only, I will put the recipe here in case someone is looking for that info,

**Comment by furlongm** [comment]
Closing as it seems like upstream docs suffice?
