### ISSUE TITLE
Errors during downloading metadata for repository 

### ISSUE THREAD

**Issue by swinomish** [furlongm/patchman#548]
Hello,

We have been using patchman for about 5-6 months now and we have started to see this issue for new installs of the patchman client

After setting up the repo and running the yum command to install the client below

We have seen an error on the repo location timing out, is there a new repo location to add?

Errors during downloading metadata for repository 'openbytes':
  - Curl error (28): Timeout was reached for https://repo.openbytes.ie/patchman/el8/repodata/repomd.xml [Connection timed out after 30000 milliseconds]
Error: Failed to download metadata for repo 'openbytes': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried

----

cat <<EOF >> /etc/yum.repos.d/openbytes.repo
[openbytes]
name=openbytes
baseurl=https://repo.openbytes.ie/patchman/el8
enabled=1
gpgcheck=0
EOF

yum -y install patchman-client

------

NAME="AlmaLinux"
VERSION="8.8 (Sapphire Caracal)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="AlmaLinux 8.8 (Sapphire Caracal)"
ANSI_COLOR="0;34"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:almalinux:almalinux:8::baseos"
HOME_URL="https://almalinux.org/"
DOCUMENTATION_URL="https://wiki.almalinux.org/"
BUG_REPORT_URL="https://bugs.almalinux.org/"

ALMALINUX_MANTISBT_PROJECT="AlmaLinux-8"
ALMALINUX_MANTISBT_PROJECT_VERSION="8.8"
REDHAT_SUPPORT_PRODUCT="AlmaLinux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.8"

**Comment by furlongm** [comment]
Can you run `curl  https://repo.openbytes.ie/patchman/el8/repodata/repomd.xml ` and see what happens?

**Comment by swinomish** [comment]
It had been working before the el19 update I believe.

curl: (7) Failed to connect to repo.openbytes.ie port 443: Connection timed out

**Comment by furlongm** [comment]
Are you behind a firewall? Or using ipv6?

Try `curl -v repo.openbytes.ie` and `curl -vL repo.openbytes.ie`

**Comment by swinomish** [comment]
found the issue, firewall was blocking by geo location

all good now..
