### ISSUE TITLE
Patchman on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by simonflood** [furlongm/patchman#57]
Installing Patchman and running "patchman-manage createsuperuser" on Ubuntu Server 18.04.1 LTS both display the following warnings:

--begin--
?: (rest_framework.W001) You have specified a default PAGE_SIZE pagination rest_framework setting,without specifying also a DEFAULT_PAGINATION_CLASS.
HINT: The default for DEFAULT_PAGINATION_CLASS is None. In previous versions this was PageNumberPagination. If you wish to define PAGE_SIZE globally whilst defining pagination_class on a per-view basis you may silence this check.
---end---

and whilst you can log in via the Patchman URL you then hit an error 500 page.

Since there is no Ubuntu 18.04 repo available for Patchman had to use the 16.04 xenial one.

**Comment by furlongm** [comment]
The warnings are fixed in master.

There are no packages for 18.04 yet, as there are still some outstanding issues.

Can you enable `DEBUG = True` in `/etc/patchman/local_settings.py` to see what is causing the 500?

**Comment by RicardoJeronimo** [comment]
Hello, hope you don't mind me hijacking the thread but I'm having the exact same problem.

Here is an excerpt of the 500:

```
Request Method: | GET
-- | --
http://10.192.5.55/patchman/dashboard/
1.11.11
OperationalError
no such table: hosts_host
/usr/lib/python2.7/dist-packages/django/db/models/sql/compiler.py in execute_sql, line 899
/usr/bin/python
2.7.15
['/usr/lib/python2.7/dist-packages',  '/usr/lib/python2.7/dist-packages/patchman',  '/usr/lib/python2.7',  '/usr/lib/python2.7/plat-x86_64-linux-gnu',  '/usr/lib/python2.7/lib-tk',  '/usr/lib/python2.7/lib-old',  '/usr/lib/python2.7/lib-dynload',  '/usr/local/lib/python2.7/dist-packages',  '/usr/lib/python2.7/dist-packages']
Tue, 13 Nov 2018 12:11:16 -0500
```

**Comment by furlongm** [comment]
@RicardoJeronimo looks like the database tables have not been created for you. If you are on bionic, try running:

`patchman-manage migrate --run-syncdb`

**Comment by simonflood** [comment]
Will have to repeat my tests to see if I hit the same error and therefore resolution. Thanks.

**Comment by nik786** [comment]
patchman-manage migrate --run-syncdb
/usr/lib64/python2.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)

usage: patchman-manage migrate [-h] [--version] [-v {0,1,2,3}]
                               [--settings SETTINGS] [--pythonpath PYTHONPATH]
                               [--traceback] [--no-color] [--noinput]
                               [--no-initial-data] [--database DATABASE]
                               [--fake] [--fake-initial] [--list]
                               [app_label] [migration_name]
patchman-manage migrate: error: unrecognized arguments: --run-syncdb

**Comment by furlongm** [comment]
Patchman on bionic should be working now. Please reopen issue if that is not the case.
