### ISSUE TITLE
Patchman does not use correct server time for reporting

### ISSUE THREAD

**Issue by Borekss** [furlongm/patchman#574]
Hello
There is the Last Report column on Hosts tab that diplays when the servers last reported to Patchman. Wrong time is displayed. It seems like there is some time zone hardcoded in Patchman that makes no sense here in Europe. Please use local time from Patchman server.

**Comment by furlongm** [comment]
Does changing the django timezone in the local settings file work for you? https://docs.djangoproject.com/en/5.0/ref/settings/#std-setting-TIME_ZONE

**Comment by Borekss** [comment]
Yes it does. Time is now in correct time zone. It's a shame that I did not look at config file.
Thank you!

**Comment by furlongm** [comment]
You're welcome, closing as resolved!
