### ISSUE TITLE
Some minor errors in the Installation guide

### ISSUE THREAD

**Issue by Borekss** [furlongm/patchman#576]
1. This command has a syntax error on the latest MySQL installed on Ubuntu 22:
GRANT ALL PRIVILEGES ON patchman.* TO patchman@localhost IDENTIFIED BY 'changeme';

correct commands:
CREATE USER 'patchman'@'localhost' IDENTIFIED BY 'changeme';
GRANT ALL PRIVILEGES ON patchman.* TO 'patchman'@'localhost';

2. Duplicate command "patchman-manage createsuperuser" in Sync Database section (allready included in Install commands).
3. Missing information that we need to set custom URL in /etc/patchman/patchman-client.conf or else apt command displays error about not being able to report to patchman.example.com.

**Comment by furlongm** [comment]
1. Updated the mysql instructions, thanks!
2. The commands are not duplicated if installing from source (or if your DB has been switched from sqlite to something else). Happy to reorganise those sections if it makes more sense though.
3. Not sure what commands are missing for this? Can you open a PR with what you think is missing?

**Comment by Borekss** [comment]
3. I mean that patchman-client.conf is not mentioned in the Installation guide at all. I suggest to create a new section in this guide named "Client installation" and include three steps
* install package patchman-client
* change "patchman.example.com" in /etc/patchman/patchman-client.conf to your_URL
* test run patchman-client -s http://your_URL/patchman/

**Comment by furlongm** [comment]
Merged your PR, thanks!
