### ISSUE TITLE
Patchman on Ubuntu 16.04 not associating additional repos with subsequent hosts

### ISSUE THREAD

**Issue by simonflood** [furlongm/patchman#58]
This is an odd one.

Patchman 1.09-1 on Ubuntu Server 16.04 LTS with fixed /usr/lib/python2.7/dist-packages/patchman/repos/utils.py as per #55.

Running "patchman-client" on Server with regular Ubuntu repos followed by "patchman -a" creates a host in Patchman with associated repos, etc. So far, so good.

Running "patchman-client" on Desktop with regular Ubuntu repos plus 8 additional ones following by "patchman -a" creates a host in Patchman but doesn't associate it with any repos. Patchman then reports that "2 Hosts have no associated Repositories", "8 Repositories are unused (no associated Hosts or OS Groups)", and "8 Repositories are not used by any Hosts". It also says (in this case) "36 Installed Packages are not from any Repository" - these packages are from the unused repos.
![screenshot from 2018-11-09 14-55-26](https://user-images.githubusercontent.com/8300801/48269464-8b82c880-e42f-11e8-9db1-d1fd19b37d7d.png)

As far as I can tell (by running "patchman-client -vr") the Desktop is sending all the necessary information for Patchman to associate repos, etc. I don't see a way of running patchman with verbosity to see what it thinks when processing - is there an option and/or debug log?

Whilst I think I could now associate Hosts with Repos I don't really want to have to do that when all our Desktops will be added.

**Comment by simonflood** [comment]
Checking the Reports tab within Patchman shows that both Repos and Packages came through in the report(s) from each Host so I don't think this is a patchman-client issue.

**Comment by simonflood** [comment]
Re-reading #55 where you asked the question"Regarding the visual studio repo, can you let me know the repo format on the machines, e.g. in /etc/apt/sources.list or in a file in /etc/apt/sources.list.d?" for the 8 odd/missing repos these are all configured via separate .list files in /etc/apt/sources.list.d/. For both the Server and Desktops the "standard" repos are all configured via /etc/apt/sources.list.

**Comment by furlongm** [comment]
Can you provide the output of the files in `/etc/apt/sources.list.d` so I can try to reproduce?

**Comment by simonflood** [comment]
Note the lines starting "# File: " are not in each file, I've just used those to label & break each file up.

# File: /etc/apt/sources.list.d/cran.list
#deb https://cran.ma.imperial.ac.uk/bin/linux/ubuntu xenial/
deb https://cloud.r-project.org/bin/linux/ubuntu xenial/

# File: /etc/apt/sources.list.d/google-chrome.list
### THIS FILE IS AUTOMATICALLY CONFIGURED ###
# You may comment out this entry, but any other modifications may be lost.
deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main

# File: /etc/apt/sources.list.d/klaus-vormweg-ubuntu-awesome-xenial.list
deb http://ppa.launchpad.net/klaus-vormweg/awesome/ubuntu xenial main
# deb-src http://ppa.launchpad.net/klaus-vormweg/awesome/ubuntu xenial main

# File: /etc/apt/sources.list.d/mendeleydesktop.list
# This file lists the repositories for Mendeley Desktop.
#
# These repositories should work with most recent Debian/Ubuntu-based Linux
# distributions.
#
# If you have any problems with Mendeley's Debian/Ubuntu repositories,
# you can let us know at http://feedback.mendeley.com
#
# The distribution name sets the release channel you want to use,
# which can be either "stable" or "preview"

deb https://desktop-download.mendeley.com/download/apt stable main

# File: /etc/apt/sources.list.d/patchman.list
deb http://repo.openbytes.ie/ubuntu xenial main

# File: /etc/apt/sources.list.d/slack.list
### THIS FILE IS AUTOMATICALLY CONFIGURED ###
# You may comment out this entry, but any other modifications may be lost.
deb https://packagecloud.io/slacktechnologies/slack/debian/ jessie main

# File: /etc/apt/sources.list.d/teamviewer.list
###   TeamViewer DEB repository list

### NOTE: Manual changes to this file
###        - prevent it from being updated by TeamViewer package updates
###        - will be lost after using the 'teamviewer repo' command
###       The original file can be restored with this command:
###       cp /opt/teamviewer/tv_bin/script/teamviewer.list /etc/apt/sources.list.d/teamviewer.list
###       which has the same effect as 'teamviewer repo default'

### NOTE: It is preferred to use the following commands to edit this file:
###       teamviewer repo                - show current repository configuration
###       teamviewer repo default        - restore default configuration
###       teamviewer repo disable        - disable the repository
###       teamviewer repo main [stable]  - make all TeamViewer packages available (default)
###       teamviewer repo tv13 [stable]  - make TeamViewer 13 packages available
###                             stable     omit preview and beta releases


### Choose stable main to receive updates for TeamViewer 13 and upcoming major releases
### Choose preview main to receive early updates for TeamViewer 13 and to receive major beta releases

### Choose stable tv13 to receive updates for TeamViewer 13
### Choose preview tv13 to receive early updates for TeamViewer 13

deb http://linux.teamviewer.com/deb stable main
deb http://linux.teamviewer.com/deb preview main

# deb http://linux.teamviewer.com/deb stable tv13
# deb http://linux.teamviewer.com/deb preview tv13

# File: /etc/apt/sources.list.d/vscode.list
### THIS FILE IS AUTOMATICALLY CONFIGURED ###
# You may comment out this entry, but any other modifications may be lost.
deb [arch=amd64] http://packages.microsoft.com/repos/vscode stable main

**Comment by furlongm** [comment]
576fd1fc4e5dc9bfcfa9860a203eb054d6a209bc caused a regression with host repo processing and deletion.

c3fcd1d4122bac84ed180af47edb132b3d07e1b4 fixes this issue and the 1.0.11 release contains this fix.

**Comment by furlongm** [comment]
1.0.11 also contains fixes for handling all the repos above. Thanks again for the examples, the client has been updated with a few fixes to handle those repos correctly.

**Comment by simonflood** [comment]
No problem. Thanks for your work on resolving this, it's all now working though the Apache configuration file got overwritten when upgrading Patchman so I'll log that as a separate issue.
