### ISSUE TITLE
[Feature Request] support pacman (arch linux)

### ISSUE THREAD

**Issue by roock** [furlongm/patchman#59]
Any plans to add support for Arch Linux (pacman)?

**Comment by furlongm** [comment]
I'd accept a PR on this any time. Doesn't seem too difficult, just parsing the various files that Arch downloads and adding a new Package format.

**Comment by ArnCo** [comment]
Yep this would be great indeed. I have loads of things on my plate right now, I'll take a look at it in a few months if nothing happens until then.

**Comment by furlongm** [comment]
@roock @ArnCo feel free to test master branch to ensure Arch Linux support is working as expected.
