### ISSUE TITLE
Outputting available updates, per host, by CLI

### ISSUE THREAD

**Issue by RicardoJeronimo** [furlongm/patchman#60]
Hi!

Is there any way I can list all the available updates for a host with CLI? I need to e-mail a weekly report with the output.

Thank you!

**Comment by simonflood** [comment]
My turn to jump in on your ticket! ;-)

Since this is possible on a per-machine basis presumably you're after one report from Patchman covering all machines?

**Comment by RicardoJeronimo** [comment]
Hi!

Yes, @furlongm, that does work and it's exactly what I needed. I'm in the process of writing a script that parses that output, given a hostname, and e-mails a report with all available updates. I'll open a pull request soon if you want to add that feature.
