### ISSUE TITLE
Error after removing an apt source

### ISSUE THREAD

**Issue by dandunckelman** [furlongm/patchman#68]
# Summary

Removing an apt source from a VM causes the patchman server to fail to process reports for that VM.

## My use-case

- I removed a package:

      apt-get purge newrelic-sysmond -y
- Removed its apt source:

      rm /etc/apt/sources.list.d/newrelic.list*
- I then ran these to sync to the patchman server 

      apt update
      patchman-client
- I then went to my patchman server and processed the report:

      patchman -a
- It threw a Python stack trace w/ this error message:

      patchman AssertionError: Repository object can't be deleted because its id attribute is set to None.

## My workaround

I found the offending repositories in the UI and deleted them manually.

Then `patchman -a` worked as expected.

**Comment by furlongm** [comment]
Thanks for the report. Can you try with 000dd12b8fc59b004f5583ce62edfad629e12fe8 and see if that fixes it?

**Comment by furlongm** [comment]
This should be fixed in 1.0.19. If not, please reopen issue.
