### ISSUE TITLE
apt post-invoke hook disabled by default through nonexistent path to patchman client

### ISSUE THREAD

**Issue by michaelweiser** [furlongm/patchman#70]
Hi Marcus,

Thanks for this great piece of kit! :) One question though:
https://github.com/furlongm/patchman/blob/5d4fba2e3f400a0fc8a896ac6e932201e58676d3/hooks/apt/05patchman#L1 looks for `/usr/sbin/patchman-client` but https://github.com/furlongm/patchman/blob/5d4fba2e3f400a0fc8a896ac6e932201e58676d3/debian/patchman-client.install#L2 installs it as `/usr/bin/patchman-client`. Therefore the hook is disabled until I either edit the hook to fix the path or create a symlink. Is that intentional and if so, how is it supposed to be used?

Thanks,
Michael

**Comment by furlongm** [comment]
Looks like I added the incorrect path, thanks for the report!
