### ISSUE TITLE
Input Sanitization

### ISSUE THREAD

**Issue by mpevner** [furlongm/patchman#78]
I'm enjoying patchman so far but have found some issues concerning RPM repos.
If the repo somehow contains a backslash [0] this breaks rather badly and will cause the server to choke on the report.
Equally, if the repository contains an apostrophe [1], this also breaks the server, causing a duplicate url error.
While it might break original formatting a little, possibly just stripping bad characters out might be the simplest, unless it's possible to find and escape them.
Aside, on rDNS checks, it should probably ignore case [3].

[0] https://docs.influxdata.com/influxdb/v1.7/introduction/installation/
```
name = InfluxDB Repository - RHEL \$releasever
baseurl = https://repos.influxdata.com/rhel/\$releasever/\$basearch/stable
```

[1] https://rpms.remirepo.net/
```
name=Remi's RPM repository for Enterprise Linux 7 - $basearch
```

[3] SVR-fserv vs. svr-fserv

**Comment by RicardoJeronimo** [comment]
I had the same problem with Remi's RPM Repository. After a lot of debugging I traced the problem back to patchman-client in lines 276 and 277, where the command returns a parsed "yum repolist enabled --verbose".

For example:
```
'base/7/x86_64' 'CentOS-7 - Base' 'http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock' 'http://centos.mirror.ptisp.pt/centos/7.6.1810/os/x86_64'

'remi-safe' 'Safe Remi's RPM repository for Enterprise Linux 7 - x86_64' 'http://cdn.remirepo.net/enterprise/7/safe/mirror' 'https://mir01.syntis.net/remirepo/enterprise/7/safe/x86_64'

```

As you can see, the fields need to be escaped in order to avoid the issue with the single quotes. To that effect, I added **-e "s/'//g"** to line 276 to remove the single quote completely: 

`yum_repolist=$(yum repolist enabled --verbose 2>/dev/null | sed -e "s/:\? *([0-9]\+ more)$//g" -e "s/ ([0-9]\+$//g" -e "s/:\? more)$//g" -e "s/'//g")`

The new output:
`'remi-safe' 'Safe Remis RPM repository for Enterprise Linux 7 - x86_64' 'http://cdn.remirepo.net/enterprise/7/safe/mirror' 'https://mir01.syntis.net/remirepo/enterprise/7/safe/x86_64'`


I hope this helps, at least until @furlongm pushes out a fix!

**Comment by furlongm** [comment]
@RicardoJeronimo thanks for the workaround, I'll add it to the client.

@mpevner I've fixed the rdns lowercasing in 61760c9. Can you test if that works for you?

@mpevner for the influxdb issue, I cannot reproduce. Can you paste the relevant output of `patchman-client -v -d`? I get the following:

```
'rpm' 'InfluxDB Repository - RHEL 7 x86_64' 'influxdb/7/x86_64' '99' 'https://repos.influxdata.com/rhel/7/x86_64/stable'
```

**Comment by mpevner** [comment]
No problem, results as follows:
```
Finding yum repos...
sed: -e expression #1, char 125: Invalid back reference
'rpm' 'CentOS-7 - Base x86_64' 'base/7/x86_64' '99' 'http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock' 'http://mirror.fileplanet.com/centos/7.6.1810/os/x86_64' 
'rpm' 'Extra Packages for Enterprise Linux 7 - x86_64 x86_64' 'epel/x86_64' '99' 'https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=x86_64' 'http://reflector.westga.edu/repos/Fedora-EPEL/7/x86_64' 
'rpm' 'CentOS-7 - Extras x86_64' 'extras/7/x86_64' '99' 'http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=extras&infra=stock' 'http://mirror.nodesdirect.com/centos/7.6.1810/extras/x86_64' 
'rpm' 
'rpm' 'nginx repo x86_64' 'nginx/x86_64' '99' 'http://nginx.org/packages/centos/7/x86_64' 
'rpm' 'Remis RPM repository for Enterprise Linux 7 - x86_64 x86_64' 'remi' '99' 'http://cdn.remirepo.net/enterprise/7/remi/mirror' 'http://repo1.ash.innoscale.net/remi/enterprise/7/remi/x86_64' 
'rpm' 'Remis PHP 5.6 RPM repository for Enterprise Linux 7 - x86_64 x86_64' 'remi-php56' '99' 'http://cdn.remirepo.net/enterprise/7/php56/mirror' 'http://repo1.ash.innoscale.net/remi/enterprise/7/php56/x86_64' 
'rpm' 'Safe Remis RPM repository for Enterprise Linux 7 - x86_64 x86_64' 'remi-safe' '99' 'http://cdn.remirepo.net/enterprise/7/safe/mirror' 'http://repo1.ash.innoscale.net/remi/enterprise/7/safe/x86_64' 
'rpm' 'CentOS-7 - Updates x86_64' 'updates/7/x86_64' '99' 'http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=updates&infra=stock' 'http://mirror.jaleco.com/centos/7.6.1810/updates/x86_64' 
```

To be fair, a backslash probably shouldn't be in a repo file like that either. I'm not sure why they have it.

**Comment by furlongm** [comment]
@mpevner Can you paste the output of `yum -C repolist -v`. I'm curious where the sed error is coming from.

**Comment by mpevner** [comment]
the relevant breaker is probably the backslash RHEL \7:
```
Repo-id      : influxdb/7/x86_64
Repo-name    : InfluxDB Repository - RHEL \7
Repo-revision: 1548196142
Repo-updated : Tue Jan 22 17:29:02 2019
Repo-pkgs    : 148
Repo-size    : 1.9 G
Repo-baseurl : https://repos.influxdata.com/rhel/7/x86_64/stable
Repo-expire  : 21,600 second(s) (last: Sun Feb  3 21:01:37 2019)
  Filter     : read-only:present
Repo-filename: /etc/yum.repos.d/influxdb.repo
```

**Comment by furlongm** [comment]
I installed using the instructions on the influxdb website and I don't see a backslash:

```
Repo-id      : influxdb/7/x86_64
Repo-name    : InfluxDB Repository - RHEL 7
Repo-revision: 1548196142
Repo-updated : Tue Jan 22 22:29:02 2019
Repo-pkgs    : 148
Repo-size    : 1.9 G
Repo-baseurl : https://repos.influxdata.com/rhel/7/x86_64/stable/
Repo-expire  : 21,600 second(s) (last: Sun Feb  3 03:36:18 2019)
  Filter     : read-only:present
Repo-filename: /etc/yum.repos.d/influxdb.repo

[root@localhost ~]# cat /etc/yum.repos.d/influxdb.repo
[influxdb]
name = InfluxDB Repository - RHEL $releasever
baseurl = https://repos.influxdata.com/rhel/$releasever/$basearch/stable
enabled = 1
gpgcheck = 1
gpgkey = https://repos.influxdata.com/influxdb.key
```

**Comment by furlongm** [comment]
If you created the file without using `cat` as they suggest, then you will have extra slashes. (i.e. if you just copy and pasted the section they provide).

**Comment by mpevner** [comment]
I don't think I've run into issues since, so it's probably safe to close this.

**Comment by enekux** [comment]
Hi,

we have the same issue from a repo from [Wazuh](https://documentation.wazuh.com/current/installation-guide/wazuh-agent/wazuh-agent-package-linux.html) where they are adding a `\` in one of the lines `name=EL-\$releasever - Wazuh`:

```
cat > /etc/yum.repos.d/wazuh.repo << EOF
[wazuh]
gpgcheck=1
gpgkey=https://packages.wazuh.com/key/GPG-KEY-WAZUH
enabled=1
name=EL-\$releasever - Wazuh
baseurl=https://packages.wazuh.com/4.x/yum/
protect=1
EOF
```

Removing it the error `sed` error does not show anymore
