### ISSUE TITLE
patchman-client: baseurl with %20 (space) 

### ISSUE THREAD

**Issue by MrDragon** [furlongm/patchman#83]
I'm pulling "bind" from bkraft's repo, and for CentOS/RHEL 6, he has this nifty baseurl:
http://bkraft.fr/files/RPM%20stuff/ - yes, a space in the URL!

when running patchman-client -d -v, this triggers:
```Finding yum repos...
awk: (FILENAME=- FNR=28) fatal: not enough arguments to satisfy format string
        `'http://bkraft.fr/files/RPM%20stuff/' '
                                      ^ ran out for this one
```
I'm not overly concerned, just wanted to point this out.

Thanks for your work!

**Comment by furlongm** [comment]
Can you check if d50ad509d65171761ccc532f3ed3c58b03e0fb51 fixes this issue?

**Comment by MrDragon** [comment]
Awesome!
Looks like it works for me - and it didn't break anything, either!
