### ISSUE TITLE
patchman installation issue

### ISSUE THREAD

**Issue by nik786** [furlongm/patchman#87]
Installation Process
cat <<EOF >> /etc/yum.repos.d/openbytes.repo
[openbytes]
name=openbytes
baseurl=http://repo.openbytes.ie/yum
enabled=1
gpgcheck=0
EOF
yum install -y epel-release
yum makecache
yum install -y patchman

cd /srv
git clone https://github.com/furlongm/patchman
cd /srv/patchman/patchman

After had installation of patchman whenever trying to execute below mentioned 

patchman-manage migrate
patchman-manage createsuperuser

Im receiving below mentioned error

"ImportError: Could not import 'rest_framework.pagination.PageNumberPagination' for API setting 'DEFAULT_PAGINATION_CLASS'. ImportError: No module named urls."

**Comment by nik786** [comment]
not solved yet.
Any solution will be appreciated

**Comment by furlongm** [comment]
What operating system are you installing on?

Also, it looks like you are installing from source _and_ installing from repo. You need to choose one of those (repo is probably best).

**Comment by furlongm** [comment]
Closing due to lack of response, please re-open if the issue persists.
