### ISSUE TITLE
add (apt) proxy support

### ISSUE THREAD

**Issue by borzel** [furlongm/patchman#89]
We hav an apt-cacher-ng as apt proxy for our local debians/ubuntus. How can I achieve that patchman uses also this proxy?

On my debian/ubuntu boxes I configure it (for example) in /etc/apt/apt-conf.d/02-proxy:
`Acquire::http::Proxy "http://<some-IP>:3142";`

**Comment by borzel** [comment]
I tried with `http_proxy=http://127.0.0.1:3128/ patchman -r`, but it failes on ftp-connections :-(

**Comment by furlongm** [comment]
Does setting ftp_proxy help?

**Comment by borzel** [comment]
Does not work for debain repositories and apt-cacher-ng because apt-cacher-ng does not work with ftp.
