### ISSUE TITLE
CentOS RPM Issues

### ISSUE THREAD

**Issue by mpevner** [furlongm/patchman#93]
I tried to spin up a fresh CentOS 7 install and found patchman didn't work using the instructions. On diagnosis, it was expecting the patchman package to be in /usr/lib/python2.7/site-packages instead of /usr/local/lib/python2.7/dist-packages as it currently is. This especially leads to the database not being made as well.

Equally, the rpm-post-install script fails to work correctly as it is unable to find patchman-manage and patchman-set-secret-key. I find this also holds true trying to call them via sudo, but does work fine from a normal user context (login / su -l; patchman-*).

I was able to work around this manually copying the packages accordingly and then manually running each line of the post-install script. After that everything works without incident so far.

I have no qualms destroying/rebuilding the virtual machine so will be happy to assist in testing.

**Comment by furlongm** [comment]
I have fixed the rpm in the repo, can you try again?

The issue was the rpm was built on Ubuntu, rather than CentOS, and this caused the incorrect paths to be used.
