### ISSUE TITLE
[Idea] Add LDAP authentication

### ISSUE THREAD

**Issue by dellarte** [furlongm/patchman#94]
Hello,

It would be nice to add an LDAP authentication.

Thanks.

Best regards

**Comment by furlongm** [comment]
You should be able to add LDAP auth as you would with any django app:

https://django-auth-ldap.readthedocs.io/en/latest/install.html

**Comment by dellarte** [comment]
Thank you for pointing me to the right direction, it's working with LDAP.
For others who want to setting up LDAP authentication, it seems that the LDAP option configuration "ldap.OPT_REFERRALS: 0" is mandatory
